/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package now.calypso.backend.data;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class Application implements org.apache.thrift.TBase<Application, Application._Fields>, java.io.Serializable, Cloneable, Comparable<Application> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Application");

  private static final org.apache.thrift.protocol.TField CLIENT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("client_id", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField CLIENT_SECRET_FIELD_DESC = new org.apache.thrift.protocol.TField("client_secret", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("name", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField REDIRECT_URI_FIELD_DESC = new org.apache.thrift.protocol.TField("redirect_uri", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField SCOPES_FIELD_DESC = new org.apache.thrift.protocol.TField("scopes", org.apache.thrift.protocol.TType.STRING, (short)5);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ApplicationStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ApplicationTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String client_id; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String client_secret; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String name; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String redirect_uri; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String scopes; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CLIENT_ID((short)1, "client_id"),
    CLIENT_SECRET((short)2, "client_secret"),
    NAME((short)3, "name"),
    REDIRECT_URI((short)4, "redirect_uri"),
    SCOPES((short)5, "scopes");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CLIENT_ID
          return CLIENT_ID;
        case 2: // CLIENT_SECRET
          return CLIENT_SECRET;
        case 3: // NAME
          return NAME;
        case 4: // REDIRECT_URI
          return REDIRECT_URI;
        case 5: // SCOPES
          return SCOPES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CLIENT_ID, new org.apache.thrift.meta_data.FieldMetaData("client_id", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CLIENT_SECRET, new org.apache.thrift.meta_data.FieldMetaData("client_secret", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.NAME, new org.apache.thrift.meta_data.FieldMetaData("name", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.REDIRECT_URI, new org.apache.thrift.meta_data.FieldMetaData("redirect_uri", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SCOPES, new org.apache.thrift.meta_data.FieldMetaData("scopes", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Application.class, metaDataMap);
  }

  public Application() {
  }

  public Application(
    java.lang.String client_id,
    java.lang.String client_secret,
    java.lang.String name,
    java.lang.String redirect_uri,
    java.lang.String scopes)
  {
    this();
    this.client_id = client_id;
    this.client_secret = client_secret;
    this.name = name;
    this.redirect_uri = redirect_uri;
    this.scopes = scopes;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Application(Application other) {
    if (other.isSetClient_id()) {
      this.client_id = other.client_id;
    }
    if (other.isSetClient_secret()) {
      this.client_secret = other.client_secret;
    }
    if (other.isSetName()) {
      this.name = other.name;
    }
    if (other.isSetRedirect_uri()) {
      this.redirect_uri = other.redirect_uri;
    }
    if (other.isSetScopes()) {
      this.scopes = other.scopes;
    }
  }

  @Override
  public Application deepCopy() {
    return new Application(this);
  }

  @Override
  public void clear() {
    this.client_id = null;
    this.client_secret = null;
    this.name = null;
    this.redirect_uri = null;
    this.scopes = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getClient_id() {
    return this.client_id;
  }

  public Application setClient_id(@org.apache.thrift.annotation.Nullable java.lang.String client_id) {
    this.client_id = client_id;
    return this;
  }

  public void unsetClient_id() {
    this.client_id = null;
  }

  /** Returns true if field client_id is set (has been assigned a value) and false otherwise */
  public boolean isSetClient_id() {
    return this.client_id != null;
  }

  public void setClient_idIsSet(boolean value) {
    if (!value) {
      this.client_id = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getClient_secret() {
    return this.client_secret;
  }

  public Application setClient_secret(@org.apache.thrift.annotation.Nullable java.lang.String client_secret) {
    this.client_secret = client_secret;
    return this;
  }

  public void unsetClient_secret() {
    this.client_secret = null;
  }

  /** Returns true if field client_secret is set (has been assigned a value) and false otherwise */
  public boolean isSetClient_secret() {
    return this.client_secret != null;
  }

  public void setClient_secretIsSet(boolean value) {
    if (!value) {
      this.client_secret = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getName() {
    return this.name;
  }

  public Application setName(@org.apache.thrift.annotation.Nullable java.lang.String name) {
    this.name = name;
    return this;
  }

  public void unsetName() {
    this.name = null;
  }

  /** Returns true if field name is set (has been assigned a value) and false otherwise */
  public boolean isSetName() {
    return this.name != null;
  }

  public void setNameIsSet(boolean value) {
    if (!value) {
      this.name = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getRedirect_uri() {
    return this.redirect_uri;
  }

  public Application setRedirect_uri(@org.apache.thrift.annotation.Nullable java.lang.String redirect_uri) {
    this.redirect_uri = redirect_uri;
    return this;
  }

  public void unsetRedirect_uri() {
    this.redirect_uri = null;
  }

  /** Returns true if field redirect_uri is set (has been assigned a value) and false otherwise */
  public boolean isSetRedirect_uri() {
    return this.redirect_uri != null;
  }

  public void setRedirect_uriIsSet(boolean value) {
    if (!value) {
      this.redirect_uri = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getScopes() {
    return this.scopes;
  }

  public Application setScopes(@org.apache.thrift.annotation.Nullable java.lang.String scopes) {
    this.scopes = scopes;
    return this;
  }

  public void unsetScopes() {
    this.scopes = null;
  }

  /** Returns true if field scopes is set (has been assigned a value) and false otherwise */
  public boolean isSetScopes() {
    return this.scopes != null;
  }

  public void setScopesIsSet(boolean value) {
    if (!value) {
      this.scopes = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case CLIENT_ID:
      if (value == null) {
        unsetClient_id();
      } else {
        setClient_id((java.lang.String)value);
      }
      break;

    case CLIENT_SECRET:
      if (value == null) {
        unsetClient_secret();
      } else {
        setClient_secret((java.lang.String)value);
      }
      break;

    case NAME:
      if (value == null) {
        unsetName();
      } else {
        setName((java.lang.String)value);
      }
      break;

    case REDIRECT_URI:
      if (value == null) {
        unsetRedirect_uri();
      } else {
        setRedirect_uri((java.lang.String)value);
      }
      break;

    case SCOPES:
      if (value == null) {
        unsetScopes();
      } else {
        setScopes((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case CLIENT_ID:
      return getClient_id();

    case CLIENT_SECRET:
      return getClient_secret();

    case NAME:
      return getName();

    case REDIRECT_URI:
      return getRedirect_uri();

    case SCOPES:
      return getScopes();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case CLIENT_ID:
      return isSetClient_id();
    case CLIENT_SECRET:
      return isSetClient_secret();
    case NAME:
      return isSetName();
    case REDIRECT_URI:
      return isSetRedirect_uri();
    case SCOPES:
      return isSetScopes();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof Application)
      return this.equals((Application)that);
    return false;
  }

  public boolean equals(Application that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_client_id = true && this.isSetClient_id();
    boolean that_present_client_id = true && that.isSetClient_id();
    if (this_present_client_id || that_present_client_id) {
      if (!(this_present_client_id && that_present_client_id))
        return false;
      if (!this.client_id.equals(that.client_id))
        return false;
    }

    boolean this_present_client_secret = true && this.isSetClient_secret();
    boolean that_present_client_secret = true && that.isSetClient_secret();
    if (this_present_client_secret || that_present_client_secret) {
      if (!(this_present_client_secret && that_present_client_secret))
        return false;
      if (!this.client_secret.equals(that.client_secret))
        return false;
    }

    boolean this_present_name = true && this.isSetName();
    boolean that_present_name = true && that.isSetName();
    if (this_present_name || that_present_name) {
      if (!(this_present_name && that_present_name))
        return false;
      if (!this.name.equals(that.name))
        return false;
    }

    boolean this_present_redirect_uri = true && this.isSetRedirect_uri();
    boolean that_present_redirect_uri = true && that.isSetRedirect_uri();
    if (this_present_redirect_uri || that_present_redirect_uri) {
      if (!(this_present_redirect_uri && that_present_redirect_uri))
        return false;
      if (!this.redirect_uri.equals(that.redirect_uri))
        return false;
    }

    boolean this_present_scopes = true && this.isSetScopes();
    boolean that_present_scopes = true && that.isSetScopes();
    if (this_present_scopes || that_present_scopes) {
      if (!(this_present_scopes && that_present_scopes))
        return false;
      if (!this.scopes.equals(that.scopes))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetClient_id()) ? 131071 : 524287);
    if (isSetClient_id())
      hashCode = hashCode * 8191 + client_id.hashCode();

    hashCode = hashCode * 8191 + ((isSetClient_secret()) ? 131071 : 524287);
    if (isSetClient_secret())
      hashCode = hashCode * 8191 + client_secret.hashCode();

    hashCode = hashCode * 8191 + ((isSetName()) ? 131071 : 524287);
    if (isSetName())
      hashCode = hashCode * 8191 + name.hashCode();

    hashCode = hashCode * 8191 + ((isSetRedirect_uri()) ? 131071 : 524287);
    if (isSetRedirect_uri())
      hashCode = hashCode * 8191 + redirect_uri.hashCode();

    hashCode = hashCode * 8191 + ((isSetScopes()) ? 131071 : 524287);
    if (isSetScopes())
      hashCode = hashCode * 8191 + scopes.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(Application other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetClient_id(), other.isSetClient_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetClient_id()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.client_id, other.client_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetClient_secret(), other.isSetClient_secret());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetClient_secret()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.client_secret, other.client_secret);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetName(), other.isSetName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.name, other.name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetRedirect_uri(), other.isSetRedirect_uri());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRedirect_uri()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.redirect_uri, other.redirect_uri);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetScopes(), other.isSetScopes());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetScopes()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.scopes, other.scopes);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Application(");
    boolean first = true;

    sb.append("client_id:");
    if (this.client_id == null) {
      sb.append("null");
    } else {
      sb.append(this.client_id);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("client_secret:");
    if (this.client_secret == null) {
      sb.append("null");
    } else {
      sb.append(this.client_secret);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("name:");
    if (this.name == null) {
      sb.append("null");
    } else {
      sb.append(this.name);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("redirect_uri:");
    if (this.redirect_uri == null) {
      sb.append("null");
    } else {
      sb.append(this.redirect_uri);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("scopes:");
    if (this.scopes == null) {
      sb.append("null");
    } else {
      sb.append(this.scopes);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (client_id == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'client_id' was not present! Struct: " + toString());
    }
    if (client_secret == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'client_secret' was not present! Struct: " + toString());
    }
    if (name == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'name' was not present! Struct: " + toString());
    }
    if (redirect_uri == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'redirect_uri' was not present! Struct: " + toString());
    }
    if (scopes == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'scopes' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ApplicationStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public ApplicationStandardScheme getScheme() {
      return new ApplicationStandardScheme();
    }
  }

  private static class ApplicationStandardScheme extends org.apache.thrift.scheme.StandardScheme<Application> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, Application struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CLIENT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.client_id = iprot.readString();
              struct.setClient_idIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CLIENT_SECRET
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.client_secret = iprot.readString();
              struct.setClient_secretIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.name = iprot.readString();
              struct.setNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // REDIRECT_URI
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.redirect_uri = iprot.readString();
              struct.setRedirect_uriIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // SCOPES
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.scopes = iprot.readString();
              struct.setScopesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, Application struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.client_id != null) {
        oprot.writeFieldBegin(CLIENT_ID_FIELD_DESC);
        oprot.writeString(struct.client_id);
        oprot.writeFieldEnd();
      }
      if (struct.client_secret != null) {
        oprot.writeFieldBegin(CLIENT_SECRET_FIELD_DESC);
        oprot.writeString(struct.client_secret);
        oprot.writeFieldEnd();
      }
      if (struct.name != null) {
        oprot.writeFieldBegin(NAME_FIELD_DESC);
        oprot.writeString(struct.name);
        oprot.writeFieldEnd();
      }
      if (struct.redirect_uri != null) {
        oprot.writeFieldBegin(REDIRECT_URI_FIELD_DESC);
        oprot.writeString(struct.redirect_uri);
        oprot.writeFieldEnd();
      }
      if (struct.scopes != null) {
        oprot.writeFieldBegin(SCOPES_FIELD_DESC);
        oprot.writeString(struct.scopes);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ApplicationTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public ApplicationTupleScheme getScheme() {
      return new ApplicationTupleScheme();
    }
  }

  private static class ApplicationTupleScheme extends org.apache.thrift.scheme.TupleScheme<Application> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Application struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.client_id);
      oprot.writeString(struct.client_secret);
      oprot.writeString(struct.name);
      oprot.writeString(struct.redirect_uri);
      oprot.writeString(struct.scopes);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Application struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.client_id = iprot.readString();
      struct.setClient_idIsSet(true);
      struct.client_secret = iprot.readString();
      struct.setClient_secretIsSet(true);
      struct.name = iprot.readString();
      struct.setNameIsSet(true);
      struct.redirect_uri = iprot.readString();
      struct.setRedirect_uriIsSet(true);
      struct.scopes = iprot.readString();
      struct.setScopesIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

