/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package now.calypso.backend.data;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class DirectMessage implements org.apache.thrift.TBase<DirectMessage, DirectMessage._Fields>, java.io.Serializable, Cloneable, Comparable<DirectMessage> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DirectMessage");

  private static final org.apache.thrift.protocol.TField MESSAGE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("messageId", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField SENDER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("senderId", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField RECEIVER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("receiverId", org.apache.thrift.protocol.TType.I64, (short)3);
  private static final org.apache.thrift.protocol.TField TEXT_FIELD_DESC = new org.apache.thrift.protocol.TField("text", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField SENT_AT_FIELD_DESC = new org.apache.thrift.protocol.TField("sentAt", org.apache.thrift.protocol.TType.I64, (short)5);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new DirectMessageStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new DirectMessageTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String messageId; // required
  public long senderId; // required
  public long receiverId; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String text; // required
  public long sentAt; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MESSAGE_ID((short)1, "messageId"),
    SENDER_ID((short)2, "senderId"),
    RECEIVER_ID((short)3, "receiverId"),
    TEXT((short)4, "text"),
    SENT_AT((short)5, "sentAt");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MESSAGE_ID
          return MESSAGE_ID;
        case 2: // SENDER_ID
          return SENDER_ID;
        case 3: // RECEIVER_ID
          return RECEIVER_ID;
        case 4: // TEXT
          return TEXT;
        case 5: // SENT_AT
          return SENT_AT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __SENDERID_ISSET_ID = 0;
  private static final int __RECEIVERID_ISSET_ID = 1;
  private static final int __SENTAT_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MESSAGE_ID, new org.apache.thrift.meta_data.FieldMetaData("messageId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SENDER_ID, new org.apache.thrift.meta_data.FieldMetaData("senderId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "AccountId")));
    tmpMap.put(_Fields.RECEIVER_ID, new org.apache.thrift.meta_data.FieldMetaData("receiverId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "AccountId")));
    tmpMap.put(_Fields.TEXT, new org.apache.thrift.meta_data.FieldMetaData("text", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SENT_AT, new org.apache.thrift.meta_data.FieldMetaData("sentAt", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "Timestamp")));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DirectMessage.class, metaDataMap);
  }

  public DirectMessage() {
  }

  public DirectMessage(
    java.lang.String messageId,
    long senderId,
    long receiverId,
    java.lang.String text,
    long sentAt)
  {
    this();
    this.messageId = messageId;
    this.senderId = senderId;
    setSenderIdIsSet(true);
    this.receiverId = receiverId;
    setReceiverIdIsSet(true);
    this.text = text;
    this.sentAt = sentAt;
    setSentAtIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DirectMessage(DirectMessage other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetMessageId()) {
      this.messageId = other.messageId;
    }
    this.senderId = other.senderId;
    this.receiverId = other.receiverId;
    if (other.isSetText()) {
      this.text = other.text;
    }
    this.sentAt = other.sentAt;
  }

  @Override
  public DirectMessage deepCopy() {
    return new DirectMessage(this);
  }

  @Override
  public void clear() {
    this.messageId = null;
    setSenderIdIsSet(false);
    this.senderId = 0;
    setReceiverIdIsSet(false);
    this.receiverId = 0;
    this.text = null;
    setSentAtIsSet(false);
    this.sentAt = 0;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getMessageId() {
    return this.messageId;
  }

  public DirectMessage setMessageId(@org.apache.thrift.annotation.Nullable java.lang.String messageId) {
    this.messageId = messageId;
    return this;
  }

  public void unsetMessageId() {
    this.messageId = null;
  }

  /** Returns true if field messageId is set (has been assigned a value) and false otherwise */
  public boolean isSetMessageId() {
    return this.messageId != null;
  }

  public void setMessageIdIsSet(boolean value) {
    if (!value) {
      this.messageId = null;
    }
  }

  public long getSenderId() {
    return this.senderId;
  }

  public DirectMessage setSenderId(long senderId) {
    this.senderId = senderId;
    setSenderIdIsSet(true);
    return this;
  }

  public void unsetSenderId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SENDERID_ISSET_ID);
  }

  /** Returns true if field senderId is set (has been assigned a value) and false otherwise */
  public boolean isSetSenderId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SENDERID_ISSET_ID);
  }

  public void setSenderIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SENDERID_ISSET_ID, value);
  }

  public long getReceiverId() {
    return this.receiverId;
  }

  public DirectMessage setReceiverId(long receiverId) {
    this.receiverId = receiverId;
    setReceiverIdIsSet(true);
    return this;
  }

  public void unsetReceiverId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __RECEIVERID_ISSET_ID);
  }

  /** Returns true if field receiverId is set (has been assigned a value) and false otherwise */
  public boolean isSetReceiverId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __RECEIVERID_ISSET_ID);
  }

  public void setReceiverIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __RECEIVERID_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getText() {
    return this.text;
  }

  public DirectMessage setText(@org.apache.thrift.annotation.Nullable java.lang.String text) {
    this.text = text;
    return this;
  }

  public void unsetText() {
    this.text = null;
  }

  /** Returns true if field text is set (has been assigned a value) and false otherwise */
  public boolean isSetText() {
    return this.text != null;
  }

  public void setTextIsSet(boolean value) {
    if (!value) {
      this.text = null;
    }
  }

  public long getSentAt() {
    return this.sentAt;
  }

  public DirectMessage setSentAt(long sentAt) {
    this.sentAt = sentAt;
    setSentAtIsSet(true);
    return this;
  }

  public void unsetSentAt() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SENTAT_ISSET_ID);
  }

  /** Returns true if field sentAt is set (has been assigned a value) and false otherwise */
  public boolean isSetSentAt() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SENTAT_ISSET_ID);
  }

  public void setSentAtIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SENTAT_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case MESSAGE_ID:
      if (value == null) {
        unsetMessageId();
      } else {
        setMessageId((java.lang.String)value);
      }
      break;

    case SENDER_ID:
      if (value == null) {
        unsetSenderId();
      } else {
        setSenderId((java.lang.Long)value);
      }
      break;

    case RECEIVER_ID:
      if (value == null) {
        unsetReceiverId();
      } else {
        setReceiverId((java.lang.Long)value);
      }
      break;

    case TEXT:
      if (value == null) {
        unsetText();
      } else {
        setText((java.lang.String)value);
      }
      break;

    case SENT_AT:
      if (value == null) {
        unsetSentAt();
      } else {
        setSentAt((java.lang.Long)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case MESSAGE_ID:
      return getMessageId();

    case SENDER_ID:
      return getSenderId();

    case RECEIVER_ID:
      return getReceiverId();

    case TEXT:
      return getText();

    case SENT_AT:
      return getSentAt();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case MESSAGE_ID:
      return isSetMessageId();
    case SENDER_ID:
      return isSetSenderId();
    case RECEIVER_ID:
      return isSetReceiverId();
    case TEXT:
      return isSetText();
    case SENT_AT:
      return isSetSentAt();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof DirectMessage)
      return this.equals((DirectMessage)that);
    return false;
  }

  public boolean equals(DirectMessage that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_messageId = true && this.isSetMessageId();
    boolean that_present_messageId = true && that.isSetMessageId();
    if (this_present_messageId || that_present_messageId) {
      if (!(this_present_messageId && that_present_messageId))
        return false;
      if (!this.messageId.equals(that.messageId))
        return false;
    }

    boolean this_present_senderId = true;
    boolean that_present_senderId = true;
    if (this_present_senderId || that_present_senderId) {
      if (!(this_present_senderId && that_present_senderId))
        return false;
      if (this.senderId != that.senderId)
        return false;
    }

    boolean this_present_receiverId = true;
    boolean that_present_receiverId = true;
    if (this_present_receiverId || that_present_receiverId) {
      if (!(this_present_receiverId && that_present_receiverId))
        return false;
      if (this.receiverId != that.receiverId)
        return false;
    }

    boolean this_present_text = true && this.isSetText();
    boolean that_present_text = true && that.isSetText();
    if (this_present_text || that_present_text) {
      if (!(this_present_text && that_present_text))
        return false;
      if (!this.text.equals(that.text))
        return false;
    }

    boolean this_present_sentAt = true;
    boolean that_present_sentAt = true;
    if (this_present_sentAt || that_present_sentAt) {
      if (!(this_present_sentAt && that_present_sentAt))
        return false;
      if (this.sentAt != that.sentAt)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetMessageId()) ? 131071 : 524287);
    if (isSetMessageId())
      hashCode = hashCode * 8191 + messageId.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(senderId);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(receiverId);

    hashCode = hashCode * 8191 + ((isSetText()) ? 131071 : 524287);
    if (isSetText())
      hashCode = hashCode * 8191 + text.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(sentAt);

    return hashCode;
  }

  @Override
  public int compareTo(DirectMessage other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetMessageId(), other.isSetMessageId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMessageId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.messageId, other.messageId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetSenderId(), other.isSetSenderId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSenderId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.senderId, other.senderId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetReceiverId(), other.isSetReceiverId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReceiverId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.receiverId, other.receiverId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetText(), other.isSetText());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetText()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.text, other.text);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetSentAt(), other.isSetSentAt());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSentAt()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sentAt, other.sentAt);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("DirectMessage(");
    boolean first = true;

    sb.append("messageId:");
    if (this.messageId == null) {
      sb.append("null");
    } else {
      sb.append(this.messageId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("senderId:");
    sb.append(this.senderId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("receiverId:");
    sb.append(this.receiverId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("text:");
    if (this.text == null) {
      sb.append("null");
    } else {
      sb.append(this.text);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("sentAt:");
    sb.append(this.sentAt);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (messageId == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'messageId' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'senderId' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'receiverId' because it's a primitive and you chose the non-beans generator.
    if (text == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'text' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'sentAt' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DirectMessageStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public DirectMessageStandardScheme getScheme() {
      return new DirectMessageStandardScheme();
    }
  }

  private static class DirectMessageStandardScheme extends org.apache.thrift.scheme.StandardScheme<DirectMessage> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, DirectMessage struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MESSAGE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.messageId = iprot.readString();
              struct.setMessageIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SENDER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.senderId = iprot.readI64();
              struct.setSenderIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // RECEIVER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.receiverId = iprot.readI64();
              struct.setReceiverIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // TEXT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.text = iprot.readString();
              struct.setTextIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // SENT_AT
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.sentAt = iprot.readI64();
              struct.setSentAtIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetSenderId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'senderId' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetReceiverId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'receiverId' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetSentAt()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'sentAt' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, DirectMessage struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.messageId != null) {
        oprot.writeFieldBegin(MESSAGE_ID_FIELD_DESC);
        oprot.writeString(struct.messageId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(SENDER_ID_FIELD_DESC);
      oprot.writeI64(struct.senderId);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(RECEIVER_ID_FIELD_DESC);
      oprot.writeI64(struct.receiverId);
      oprot.writeFieldEnd();
      if (struct.text != null) {
        oprot.writeFieldBegin(TEXT_FIELD_DESC);
        oprot.writeString(struct.text);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(SENT_AT_FIELD_DESC);
      oprot.writeI64(struct.sentAt);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DirectMessageTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public DirectMessageTupleScheme getScheme() {
      return new DirectMessageTupleScheme();
    }
  }

  private static class DirectMessageTupleScheme extends org.apache.thrift.scheme.TupleScheme<DirectMessage> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, DirectMessage struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.messageId);
      oprot.writeI64(struct.senderId);
      oprot.writeI64(struct.receiverId);
      oprot.writeString(struct.text);
      oprot.writeI64(struct.sentAt);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, DirectMessage struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.messageId = iprot.readString();
      struct.setMessageIdIsSet(true);
      struct.senderId = iprot.readI64();
      struct.setSenderIdIsSet(true);
      struct.receiverId = iprot.readI64();
      struct.setReceiverIdIsSet(true);
      struct.text = iprot.readString();
      struct.setTextIsSet(true);
      struct.sentAt = iprot.readI64();
      struct.setSentAtIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

