/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package now.calypso.backend.data;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class Filters implements org.apache.thrift.TBase<Filters, Filters._Fields>, java.io.Serializable, Cloneable, Comparable<Filters> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Filters");

  private static final org.apache.thrift.protocol.TField ACCOUNT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("accountId", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField RELATIONSHIP_MODE_FIELD_DESC = new org.apache.thrift.protocol.TField("relationshipMode", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField GENDER_FIELD_DESC = new org.apache.thrift.protocol.TField("gender", org.apache.thrift.protocol.TType.STRUCT, (short)3);
  private static final org.apache.thrift.protocol.TField AGE_FIELD_DESC = new org.apache.thrift.protocol.TField("age", org.apache.thrift.protocol.TType.STRUCT, (short)4);
  private static final org.apache.thrift.protocol.TField LOCATION_FIELD_DESC = new org.apache.thrift.protocol.TField("location", org.apache.thrift.protocol.TType.STRUCT, (short)5);
  private static final org.apache.thrift.protocol.TField RELIGION_FIELD_DESC = new org.apache.thrift.protocol.TField("religion", org.apache.thrift.protocol.TType.STRUCT, (short)6);
  private static final org.apache.thrift.protocol.TField POLITICS_FIELD_DESC = new org.apache.thrift.protocol.TField("politics", org.apache.thrift.protocol.TType.STRUCT, (short)7);
  private static final org.apache.thrift.protocol.TField LIFESTYLE_FIELD_DESC = new org.apache.thrift.protocol.TField("lifestyle", org.apache.thrift.protocol.TType.STRUCT, (short)8);
  private static final org.apache.thrift.protocol.TField INTERESTS_FIELD_DESC = new org.apache.thrift.protocol.TField("interests", org.apache.thrift.protocol.TType.STRUCT, (short)9);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new FiltersStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new FiltersTupleSchemeFactory();

  public long accountId; // required
  public @org.apache.thrift.annotation.Nullable ModeFilter relationshipMode; // required
  public @org.apache.thrift.annotation.Nullable OneToManyFilter gender; // required
  public @org.apache.thrift.annotation.Nullable RangeFilter age; // required
  public @org.apache.thrift.annotation.Nullable LocationFilter location; // required
  public @org.apache.thrift.annotation.Nullable OneToManyFilter religion; // optional
  public @org.apache.thrift.annotation.Nullable OneToManyFilter politics; // optional
  public @org.apache.thrift.annotation.Nullable ManyToManyFilter lifestyle; // optional
  public @org.apache.thrift.annotation.Nullable ManyToManyFilter interests; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ACCOUNT_ID((short)1, "accountId"),
    RELATIONSHIP_MODE((short)2, "relationshipMode"),
    GENDER((short)3, "gender"),
    AGE((short)4, "age"),
    LOCATION((short)5, "location"),
    RELIGION((short)6, "religion"),
    POLITICS((short)7, "politics"),
    LIFESTYLE((short)8, "lifestyle"),
    INTERESTS((short)9, "interests");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ACCOUNT_ID
          return ACCOUNT_ID;
        case 2: // RELATIONSHIP_MODE
          return RELATIONSHIP_MODE;
        case 3: // GENDER
          return GENDER;
        case 4: // AGE
          return AGE;
        case 5: // LOCATION
          return LOCATION;
        case 6: // RELIGION
          return RELIGION;
        case 7: // POLITICS
          return POLITICS;
        case 8: // LIFESTYLE
          return LIFESTYLE;
        case 9: // INTERESTS
          return INTERESTS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ACCOUNTID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private static final _Fields[] optionals = {_Fields.RELIGION,_Fields.POLITICS,_Fields.LIFESTYLE,_Fields.INTERESTS};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ACCOUNT_ID, new org.apache.thrift.meta_data.FieldMetaData("accountId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "AccountId")));
    tmpMap.put(_Fields.RELATIONSHIP_MODE, new org.apache.thrift.meta_data.FieldMetaData("relationshipMode", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ModeFilter.class)));
    tmpMap.put(_Fields.GENDER, new org.apache.thrift.meta_data.FieldMetaData("gender", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, OneToManyFilter.class)));
    tmpMap.put(_Fields.AGE, new org.apache.thrift.meta_data.FieldMetaData("age", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, RangeFilter.class)));
    tmpMap.put(_Fields.LOCATION, new org.apache.thrift.meta_data.FieldMetaData("location", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, LocationFilter.class)));
    tmpMap.put(_Fields.RELIGION, new org.apache.thrift.meta_data.FieldMetaData("religion", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, OneToManyFilter.class)));
    tmpMap.put(_Fields.POLITICS, new org.apache.thrift.meta_data.FieldMetaData("politics", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, OneToManyFilter.class)));
    tmpMap.put(_Fields.LIFESTYLE, new org.apache.thrift.meta_data.FieldMetaData("lifestyle", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ManyToManyFilter.class)));
    tmpMap.put(_Fields.INTERESTS, new org.apache.thrift.meta_data.FieldMetaData("interests", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ManyToManyFilter.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Filters.class, metaDataMap);
  }

  public Filters() {
  }

  public Filters(
    long accountId,
    ModeFilter relationshipMode,
    OneToManyFilter gender,
    RangeFilter age,
    LocationFilter location)
  {
    this();
    this.accountId = accountId;
    setAccountIdIsSet(true);
    this.relationshipMode = relationshipMode;
    this.gender = gender;
    this.age = age;
    this.location = location;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Filters(Filters other) {
    __isset_bitfield = other.__isset_bitfield;
    this.accountId = other.accountId;
    if (other.isSetRelationshipMode()) {
      this.relationshipMode = new ModeFilter(other.relationshipMode);
    }
    if (other.isSetGender()) {
      this.gender = new OneToManyFilter(other.gender);
    }
    if (other.isSetAge()) {
      this.age = new RangeFilter(other.age);
    }
    if (other.isSetLocation()) {
      this.location = new LocationFilter(other.location);
    }
    if (other.isSetReligion()) {
      this.religion = new OneToManyFilter(other.religion);
    }
    if (other.isSetPolitics()) {
      this.politics = new OneToManyFilter(other.politics);
    }
    if (other.isSetLifestyle()) {
      this.lifestyle = new ManyToManyFilter(other.lifestyle);
    }
    if (other.isSetInterests()) {
      this.interests = new ManyToManyFilter(other.interests);
    }
  }

  @Override
  public Filters deepCopy() {
    return new Filters(this);
  }

  @Override
  public void clear() {
    setAccountIdIsSet(false);
    this.accountId = 0;
    this.relationshipMode = null;
    this.gender = null;
    this.age = null;
    this.location = null;
    this.religion = null;
    this.politics = null;
    this.lifestyle = null;
    this.interests = null;
  }

  public long getAccountId() {
    return this.accountId;
  }

  public Filters setAccountId(long accountId) {
    this.accountId = accountId;
    setAccountIdIsSet(true);
    return this;
  }

  public void unsetAccountId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ACCOUNTID_ISSET_ID);
  }

  /** Returns true if field accountId is set (has been assigned a value) and false otherwise */
  public boolean isSetAccountId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ACCOUNTID_ISSET_ID);
  }

  public void setAccountIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ACCOUNTID_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public ModeFilter getRelationshipMode() {
    return this.relationshipMode;
  }

  public Filters setRelationshipMode(@org.apache.thrift.annotation.Nullable ModeFilter relationshipMode) {
    this.relationshipMode = relationshipMode;
    return this;
  }

  public void unsetRelationshipMode() {
    this.relationshipMode = null;
  }

  /** Returns true if field relationshipMode is set (has been assigned a value) and false otherwise */
  public boolean isSetRelationshipMode() {
    return this.relationshipMode != null;
  }

  public void setRelationshipModeIsSet(boolean value) {
    if (!value) {
      this.relationshipMode = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public OneToManyFilter getGender() {
    return this.gender;
  }

  public Filters setGender(@org.apache.thrift.annotation.Nullable OneToManyFilter gender) {
    this.gender = gender;
    return this;
  }

  public void unsetGender() {
    this.gender = null;
  }

  /** Returns true if field gender is set (has been assigned a value) and false otherwise */
  public boolean isSetGender() {
    return this.gender != null;
  }

  public void setGenderIsSet(boolean value) {
    if (!value) {
      this.gender = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public RangeFilter getAge() {
    return this.age;
  }

  public Filters setAge(@org.apache.thrift.annotation.Nullable RangeFilter age) {
    this.age = age;
    return this;
  }

  public void unsetAge() {
    this.age = null;
  }

  /** Returns true if field age is set (has been assigned a value) and false otherwise */
  public boolean isSetAge() {
    return this.age != null;
  }

  public void setAgeIsSet(boolean value) {
    if (!value) {
      this.age = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public LocationFilter getLocation() {
    return this.location;
  }

  public Filters setLocation(@org.apache.thrift.annotation.Nullable LocationFilter location) {
    this.location = location;
    return this;
  }

  public void unsetLocation() {
    this.location = null;
  }

  /** Returns true if field location is set (has been assigned a value) and false otherwise */
  public boolean isSetLocation() {
    return this.location != null;
  }

  public void setLocationIsSet(boolean value) {
    if (!value) {
      this.location = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public OneToManyFilter getReligion() {
    return this.religion;
  }

  public Filters setReligion(@org.apache.thrift.annotation.Nullable OneToManyFilter religion) {
    this.religion = religion;
    return this;
  }

  public void unsetReligion() {
    this.religion = null;
  }

  /** Returns true if field religion is set (has been assigned a value) and false otherwise */
  public boolean isSetReligion() {
    return this.religion != null;
  }

  public void setReligionIsSet(boolean value) {
    if (!value) {
      this.religion = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public OneToManyFilter getPolitics() {
    return this.politics;
  }

  public Filters setPolitics(@org.apache.thrift.annotation.Nullable OneToManyFilter politics) {
    this.politics = politics;
    return this;
  }

  public void unsetPolitics() {
    this.politics = null;
  }

  /** Returns true if field politics is set (has been assigned a value) and false otherwise */
  public boolean isSetPolitics() {
    return this.politics != null;
  }

  public void setPoliticsIsSet(boolean value) {
    if (!value) {
      this.politics = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public ManyToManyFilter getLifestyle() {
    return this.lifestyle;
  }

  public Filters setLifestyle(@org.apache.thrift.annotation.Nullable ManyToManyFilter lifestyle) {
    this.lifestyle = lifestyle;
    return this;
  }

  public void unsetLifestyle() {
    this.lifestyle = null;
  }

  /** Returns true if field lifestyle is set (has been assigned a value) and false otherwise */
  public boolean isSetLifestyle() {
    return this.lifestyle != null;
  }

  public void setLifestyleIsSet(boolean value) {
    if (!value) {
      this.lifestyle = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public ManyToManyFilter getInterests() {
    return this.interests;
  }

  public Filters setInterests(@org.apache.thrift.annotation.Nullable ManyToManyFilter interests) {
    this.interests = interests;
    return this;
  }

  public void unsetInterests() {
    this.interests = null;
  }

  /** Returns true if field interests is set (has been assigned a value) and false otherwise */
  public boolean isSetInterests() {
    return this.interests != null;
  }

  public void setInterestsIsSet(boolean value) {
    if (!value) {
      this.interests = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case ACCOUNT_ID:
      if (value == null) {
        unsetAccountId();
      } else {
        setAccountId((java.lang.Long)value);
      }
      break;

    case RELATIONSHIP_MODE:
      if (value == null) {
        unsetRelationshipMode();
      } else {
        setRelationshipMode((ModeFilter)value);
      }
      break;

    case GENDER:
      if (value == null) {
        unsetGender();
      } else {
        setGender((OneToManyFilter)value);
      }
      break;

    case AGE:
      if (value == null) {
        unsetAge();
      } else {
        setAge((RangeFilter)value);
      }
      break;

    case LOCATION:
      if (value == null) {
        unsetLocation();
      } else {
        setLocation((LocationFilter)value);
      }
      break;

    case RELIGION:
      if (value == null) {
        unsetReligion();
      } else {
        setReligion((OneToManyFilter)value);
      }
      break;

    case POLITICS:
      if (value == null) {
        unsetPolitics();
      } else {
        setPolitics((OneToManyFilter)value);
      }
      break;

    case LIFESTYLE:
      if (value == null) {
        unsetLifestyle();
      } else {
        setLifestyle((ManyToManyFilter)value);
      }
      break;

    case INTERESTS:
      if (value == null) {
        unsetInterests();
      } else {
        setInterests((ManyToManyFilter)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ACCOUNT_ID:
      return getAccountId();

    case RELATIONSHIP_MODE:
      return getRelationshipMode();

    case GENDER:
      return getGender();

    case AGE:
      return getAge();

    case LOCATION:
      return getLocation();

    case RELIGION:
      return getReligion();

    case POLITICS:
      return getPolitics();

    case LIFESTYLE:
      return getLifestyle();

    case INTERESTS:
      return getInterests();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ACCOUNT_ID:
      return isSetAccountId();
    case RELATIONSHIP_MODE:
      return isSetRelationshipMode();
    case GENDER:
      return isSetGender();
    case AGE:
      return isSetAge();
    case LOCATION:
      return isSetLocation();
    case RELIGION:
      return isSetReligion();
    case POLITICS:
      return isSetPolitics();
    case LIFESTYLE:
      return isSetLifestyle();
    case INTERESTS:
      return isSetInterests();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof Filters)
      return this.equals((Filters)that);
    return false;
  }

  public boolean equals(Filters that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_accountId = true;
    boolean that_present_accountId = true;
    if (this_present_accountId || that_present_accountId) {
      if (!(this_present_accountId && that_present_accountId))
        return false;
      if (this.accountId != that.accountId)
        return false;
    }

    boolean this_present_relationshipMode = true && this.isSetRelationshipMode();
    boolean that_present_relationshipMode = true && that.isSetRelationshipMode();
    if (this_present_relationshipMode || that_present_relationshipMode) {
      if (!(this_present_relationshipMode && that_present_relationshipMode))
        return false;
      if (!this.relationshipMode.equals(that.relationshipMode))
        return false;
    }

    boolean this_present_gender = true && this.isSetGender();
    boolean that_present_gender = true && that.isSetGender();
    if (this_present_gender || that_present_gender) {
      if (!(this_present_gender && that_present_gender))
        return false;
      if (!this.gender.equals(that.gender))
        return false;
    }

    boolean this_present_age = true && this.isSetAge();
    boolean that_present_age = true && that.isSetAge();
    if (this_present_age || that_present_age) {
      if (!(this_present_age && that_present_age))
        return false;
      if (!this.age.equals(that.age))
        return false;
    }

    boolean this_present_location = true && this.isSetLocation();
    boolean that_present_location = true && that.isSetLocation();
    if (this_present_location || that_present_location) {
      if (!(this_present_location && that_present_location))
        return false;
      if (!this.location.equals(that.location))
        return false;
    }

    boolean this_present_religion = true && this.isSetReligion();
    boolean that_present_religion = true && that.isSetReligion();
    if (this_present_religion || that_present_religion) {
      if (!(this_present_religion && that_present_religion))
        return false;
      if (!this.religion.equals(that.religion))
        return false;
    }

    boolean this_present_politics = true && this.isSetPolitics();
    boolean that_present_politics = true && that.isSetPolitics();
    if (this_present_politics || that_present_politics) {
      if (!(this_present_politics && that_present_politics))
        return false;
      if (!this.politics.equals(that.politics))
        return false;
    }

    boolean this_present_lifestyle = true && this.isSetLifestyle();
    boolean that_present_lifestyle = true && that.isSetLifestyle();
    if (this_present_lifestyle || that_present_lifestyle) {
      if (!(this_present_lifestyle && that_present_lifestyle))
        return false;
      if (!this.lifestyle.equals(that.lifestyle))
        return false;
    }

    boolean this_present_interests = true && this.isSetInterests();
    boolean that_present_interests = true && that.isSetInterests();
    if (this_present_interests || that_present_interests) {
      if (!(this_present_interests && that_present_interests))
        return false;
      if (!this.interests.equals(that.interests))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(accountId);

    hashCode = hashCode * 8191 + ((isSetRelationshipMode()) ? 131071 : 524287);
    if (isSetRelationshipMode())
      hashCode = hashCode * 8191 + relationshipMode.hashCode();

    hashCode = hashCode * 8191 + ((isSetGender()) ? 131071 : 524287);
    if (isSetGender())
      hashCode = hashCode * 8191 + gender.hashCode();

    hashCode = hashCode * 8191 + ((isSetAge()) ? 131071 : 524287);
    if (isSetAge())
      hashCode = hashCode * 8191 + age.hashCode();

    hashCode = hashCode * 8191 + ((isSetLocation()) ? 131071 : 524287);
    if (isSetLocation())
      hashCode = hashCode * 8191 + location.hashCode();

    hashCode = hashCode * 8191 + ((isSetReligion()) ? 131071 : 524287);
    if (isSetReligion())
      hashCode = hashCode * 8191 + religion.hashCode();

    hashCode = hashCode * 8191 + ((isSetPolitics()) ? 131071 : 524287);
    if (isSetPolitics())
      hashCode = hashCode * 8191 + politics.hashCode();

    hashCode = hashCode * 8191 + ((isSetLifestyle()) ? 131071 : 524287);
    if (isSetLifestyle())
      hashCode = hashCode * 8191 + lifestyle.hashCode();

    hashCode = hashCode * 8191 + ((isSetInterests()) ? 131071 : 524287);
    if (isSetInterests())
      hashCode = hashCode * 8191 + interests.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(Filters other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetAccountId(), other.isSetAccountId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAccountId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.accountId, other.accountId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetRelationshipMode(), other.isSetRelationshipMode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRelationshipMode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.relationshipMode, other.relationshipMode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetGender(), other.isSetGender());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGender()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.gender, other.gender);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetAge(), other.isSetAge());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAge()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.age, other.age);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetLocation(), other.isSetLocation());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLocation()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.location, other.location);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetReligion(), other.isSetReligion());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReligion()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.religion, other.religion);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetPolitics(), other.isSetPolitics());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPolitics()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.politics, other.politics);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetLifestyle(), other.isSetLifestyle());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLifestyle()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lifestyle, other.lifestyle);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetInterests(), other.isSetInterests());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetInterests()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.interests, other.interests);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Filters(");
    boolean first = true;

    sb.append("accountId:");
    sb.append(this.accountId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("relationshipMode:");
    if (this.relationshipMode == null) {
      sb.append("null");
    } else {
      sb.append(this.relationshipMode);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("gender:");
    if (this.gender == null) {
      sb.append("null");
    } else {
      sb.append(this.gender);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("age:");
    if (this.age == null) {
      sb.append("null");
    } else {
      sb.append(this.age);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("location:");
    if (this.location == null) {
      sb.append("null");
    } else {
      sb.append(this.location);
    }
    first = false;
    if (isSetReligion()) {
      if (!first) sb.append(", ");
      sb.append("religion:");
      if (this.religion == null) {
        sb.append("null");
      } else {
        sb.append(this.religion);
      }
      first = false;
    }
    if (isSetPolitics()) {
      if (!first) sb.append(", ");
      sb.append("politics:");
      if (this.politics == null) {
        sb.append("null");
      } else {
        sb.append(this.politics);
      }
      first = false;
    }
    if (isSetLifestyle()) {
      if (!first) sb.append(", ");
      sb.append("lifestyle:");
      if (this.lifestyle == null) {
        sb.append("null");
      } else {
        sb.append(this.lifestyle);
      }
      first = false;
    }
    if (isSetInterests()) {
      if (!first) sb.append(", ");
      sb.append("interests:");
      if (this.interests == null) {
        sb.append("null");
      } else {
        sb.append(this.interests);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'accountId' because it's a primitive and you chose the non-beans generator.
    if (relationshipMode == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'relationshipMode' was not present! Struct: " + toString());
    }
    if (gender == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'gender' was not present! Struct: " + toString());
    }
    if (age == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'age' was not present! Struct: " + toString());
    }
    if (location == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'location' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
    if (relationshipMode != null) {
      relationshipMode.validate();
    }
    if (gender != null) {
      gender.validate();
    }
    if (age != null) {
      age.validate();
    }
    if (location != null) {
      location.validate();
    }
    if (religion != null) {
      religion.validate();
    }
    if (politics != null) {
      politics.validate();
    }
    if (lifestyle != null) {
      lifestyle.validate();
    }
    if (interests != null) {
      interests.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class FiltersStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public FiltersStandardScheme getScheme() {
      return new FiltersStandardScheme();
    }
  }

  private static class FiltersStandardScheme extends org.apache.thrift.scheme.StandardScheme<Filters> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, Filters struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ACCOUNT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.accountId = iprot.readI64();
              struct.setAccountIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // RELATIONSHIP_MODE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.relationshipMode = new ModeFilter();
              struct.relationshipMode.read(iprot);
              struct.setRelationshipModeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // GENDER
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.gender = new OneToManyFilter();
              struct.gender.read(iprot);
              struct.setGenderIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // AGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.age = new RangeFilter();
              struct.age.read(iprot);
              struct.setAgeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // LOCATION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.location = new LocationFilter();
              struct.location.read(iprot);
              struct.setLocationIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // RELIGION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.religion = new OneToManyFilter();
              struct.religion.read(iprot);
              struct.setReligionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // POLITICS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.politics = new OneToManyFilter();
              struct.politics.read(iprot);
              struct.setPoliticsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // LIFESTYLE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.lifestyle = new ManyToManyFilter();
              struct.lifestyle.read(iprot);
              struct.setLifestyleIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // INTERESTS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.interests = new ManyToManyFilter();
              struct.interests.read(iprot);
              struct.setInterestsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetAccountId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'accountId' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, Filters struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ACCOUNT_ID_FIELD_DESC);
      oprot.writeI64(struct.accountId);
      oprot.writeFieldEnd();
      if (struct.relationshipMode != null) {
        oprot.writeFieldBegin(RELATIONSHIP_MODE_FIELD_DESC);
        struct.relationshipMode.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.gender != null) {
        oprot.writeFieldBegin(GENDER_FIELD_DESC);
        struct.gender.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.age != null) {
        oprot.writeFieldBegin(AGE_FIELD_DESC);
        struct.age.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.location != null) {
        oprot.writeFieldBegin(LOCATION_FIELD_DESC);
        struct.location.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.religion != null) {
        if (struct.isSetReligion()) {
          oprot.writeFieldBegin(RELIGION_FIELD_DESC);
          struct.religion.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.politics != null) {
        if (struct.isSetPolitics()) {
          oprot.writeFieldBegin(POLITICS_FIELD_DESC);
          struct.politics.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.lifestyle != null) {
        if (struct.isSetLifestyle()) {
          oprot.writeFieldBegin(LIFESTYLE_FIELD_DESC);
          struct.lifestyle.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.interests != null) {
        if (struct.isSetInterests()) {
          oprot.writeFieldBegin(INTERESTS_FIELD_DESC);
          struct.interests.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class FiltersTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public FiltersTupleScheme getScheme() {
      return new FiltersTupleScheme();
    }
  }

  private static class FiltersTupleScheme extends org.apache.thrift.scheme.TupleScheme<Filters> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Filters struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeI64(struct.accountId);
      struct.relationshipMode.write(oprot);
      struct.gender.write(oprot);
      struct.age.write(oprot);
      struct.location.write(oprot);
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetReligion()) {
        optionals.set(0);
      }
      if (struct.isSetPolitics()) {
        optionals.set(1);
      }
      if (struct.isSetLifestyle()) {
        optionals.set(2);
      }
      if (struct.isSetInterests()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetReligion()) {
        struct.religion.write(oprot);
      }
      if (struct.isSetPolitics()) {
        struct.politics.write(oprot);
      }
      if (struct.isSetLifestyle()) {
        struct.lifestyle.write(oprot);
      }
      if (struct.isSetInterests()) {
        struct.interests.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Filters struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.accountId = iprot.readI64();
      struct.setAccountIdIsSet(true);
      struct.relationshipMode = new ModeFilter();
      struct.relationshipMode.read(iprot);
      struct.setRelationshipModeIsSet(true);
      struct.gender = new OneToManyFilter();
      struct.gender.read(iprot);
      struct.setGenderIsSet(true);
      struct.age = new RangeFilter();
      struct.age.read(iprot);
      struct.setAgeIsSet(true);
      struct.location = new LocationFilter();
      struct.location.read(iprot);
      struct.setLocationIsSet(true);
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.religion = new OneToManyFilter();
        struct.religion.read(iprot);
        struct.setReligionIsSet(true);
      }
      if (incoming.get(1)) {
        struct.politics = new OneToManyFilter();
        struct.politics.read(iprot);
        struct.setPoliticsIsSet(true);
      }
      if (incoming.get(2)) {
        struct.lifestyle = new ManyToManyFilter();
        struct.lifestyle.read(iprot);
        struct.setLifestyleIsSet(true);
      }
      if (incoming.get(3)) {
        struct.interests = new ManyToManyFilter();
        struct.interests.read(iprot);
        struct.setInterestsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

