/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package now.calypso.backend.data;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class LocationFilter implements org.apache.thrift.TBase<LocationFilter, LocationFilter._Fields>, java.io.Serializable, Cloneable, Comparable<LocationFilter> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("LocationFilter");

  private static final org.apache.thrift.protocol.TField LAT_FIELD_DESC = new org.apache.thrift.protocol.TField("lat", org.apache.thrift.protocol.TType.DOUBLE, (short)1);
  private static final org.apache.thrift.protocol.TField LON_FIELD_DESC = new org.apache.thrift.protocol.TField("lon", org.apache.thrift.protocol.TType.DOUBLE, (short)2);
  private static final org.apache.thrift.protocol.TField RADIUS_KM_FIELD_DESC = new org.apache.thrift.protocol.TField("radiusKm", org.apache.thrift.protocol.TType.DOUBLE, (short)3);
  private static final org.apache.thrift.protocol.TField IMPORTANCE_FIELD_DESC = new org.apache.thrift.protocol.TField("importance", org.apache.thrift.protocol.TType.I32, (short)4);
  private static final org.apache.thrift.protocol.TField SCOPE_FIELD_DESC = new org.apache.thrift.protocol.TField("scope", org.apache.thrift.protocol.TType.I32, (short)5);
  private static final org.apache.thrift.protocol.TField COUNTRY_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("countryCode", org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.thrift.protocol.TField DISTANCE_UNIT_FIELD_DESC = new org.apache.thrift.protocol.TField("distanceUnit", org.apache.thrift.protocol.TType.I32, (short)7);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new LocationFilterStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new LocationFilterTupleSchemeFactory();

  public double lat; // required
  public double lon; // required
  public double radiusKm; // required
  /**
   * 
   * @see Importance
   */
  public @org.apache.thrift.annotation.Nullable Importance importance; // optional
  /**
   * 
   * @see LocationScope
   */
  public @org.apache.thrift.annotation.Nullable LocationScope scope; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String countryCode; // optional
  /**
   * 
   * @see DistanceUnit
   */
  public @org.apache.thrift.annotation.Nullable DistanceUnit distanceUnit; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    LAT((short)1, "lat"),
    LON((short)2, "lon"),
    RADIUS_KM((short)3, "radiusKm"),
    /**
     * 
     * @see Importance
     */
    IMPORTANCE((short)4, "importance"),
    /**
     * 
     * @see LocationScope
     */
    SCOPE((short)5, "scope"),
    COUNTRY_CODE((short)6, "countryCode"),
    /**
     * 
     * @see DistanceUnit
     */
    DISTANCE_UNIT((short)7, "distanceUnit");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // LAT
          return LAT;
        case 2: // LON
          return LON;
        case 3: // RADIUS_KM
          return RADIUS_KM;
        case 4: // IMPORTANCE
          return IMPORTANCE;
        case 5: // SCOPE
          return SCOPE;
        case 6: // COUNTRY_CODE
          return COUNTRY_CODE;
        case 7: // DISTANCE_UNIT
          return DISTANCE_UNIT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __LAT_ISSET_ID = 0;
  private static final int __LON_ISSET_ID = 1;
  private static final int __RADIUSKM_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  private static final _Fields[] optionals = {_Fields.IMPORTANCE,_Fields.SCOPE,_Fields.COUNTRY_CODE,_Fields.DISTANCE_UNIT};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.LAT, new org.apache.thrift.meta_data.FieldMetaData("lat", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.LON, new org.apache.thrift.meta_data.FieldMetaData("lon", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.RADIUS_KM, new org.apache.thrift.meta_data.FieldMetaData("radiusKm", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.IMPORTANCE, new org.apache.thrift.meta_data.FieldMetaData("importance", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, Importance.class)));
    tmpMap.put(_Fields.SCOPE, new org.apache.thrift.meta_data.FieldMetaData("scope", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, LocationScope.class)));
    tmpMap.put(_Fields.COUNTRY_CODE, new org.apache.thrift.meta_data.FieldMetaData("countryCode", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DISTANCE_UNIT, new org.apache.thrift.meta_data.FieldMetaData("distanceUnit", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, DistanceUnit.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(LocationFilter.class, metaDataMap);
  }

  public LocationFilter() {
  }

  public LocationFilter(
    double lat,
    double lon,
    double radiusKm)
  {
    this();
    this.lat = lat;
    setLatIsSet(true);
    this.lon = lon;
    setLonIsSet(true);
    this.radiusKm = radiusKm;
    setRadiusKmIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public LocationFilter(LocationFilter other) {
    __isset_bitfield = other.__isset_bitfield;
    this.lat = other.lat;
    this.lon = other.lon;
    this.radiusKm = other.radiusKm;
    if (other.isSetImportance()) {
      this.importance = other.importance;
    }
    if (other.isSetScope()) {
      this.scope = other.scope;
    }
    if (other.isSetCountryCode()) {
      this.countryCode = other.countryCode;
    }
    if (other.isSetDistanceUnit()) {
      this.distanceUnit = other.distanceUnit;
    }
  }

  @Override
  public LocationFilter deepCopy() {
    return new LocationFilter(this);
  }

  @Override
  public void clear() {
    setLatIsSet(false);
    this.lat = 0.0;
    setLonIsSet(false);
    this.lon = 0.0;
    setRadiusKmIsSet(false);
    this.radiusKm = 0.0;
    this.importance = null;
    this.scope = null;
    this.countryCode = null;
    this.distanceUnit = null;
  }

  public double getLat() {
    return this.lat;
  }

  public LocationFilter setLat(double lat) {
    this.lat = lat;
    setLatIsSet(true);
    return this;
  }

  public void unsetLat() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __LAT_ISSET_ID);
  }

  /** Returns true if field lat is set (has been assigned a value) and false otherwise */
  public boolean isSetLat() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __LAT_ISSET_ID);
  }

  public void setLatIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __LAT_ISSET_ID, value);
  }

  public double getLon() {
    return this.lon;
  }

  public LocationFilter setLon(double lon) {
    this.lon = lon;
    setLonIsSet(true);
    return this;
  }

  public void unsetLon() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __LON_ISSET_ID);
  }

  /** Returns true if field lon is set (has been assigned a value) and false otherwise */
  public boolean isSetLon() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __LON_ISSET_ID);
  }

  public void setLonIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __LON_ISSET_ID, value);
  }

  public double getRadiusKm() {
    return this.radiusKm;
  }

  public LocationFilter setRadiusKm(double radiusKm) {
    this.radiusKm = radiusKm;
    setRadiusKmIsSet(true);
    return this;
  }

  public void unsetRadiusKm() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __RADIUSKM_ISSET_ID);
  }

  /** Returns true if field radiusKm is set (has been assigned a value) and false otherwise */
  public boolean isSetRadiusKm() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __RADIUSKM_ISSET_ID);
  }

  public void setRadiusKmIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __RADIUSKM_ISSET_ID, value);
  }

  /**
   * 
   * @see Importance
   */
  @org.apache.thrift.annotation.Nullable
  public Importance getImportance() {
    return this.importance;
  }

  /**
   * 
   * @see Importance
   */
  public LocationFilter setImportance(@org.apache.thrift.annotation.Nullable Importance importance) {
    this.importance = importance;
    return this;
  }

  public void unsetImportance() {
    this.importance = null;
  }

  /** Returns true if field importance is set (has been assigned a value) and false otherwise */
  public boolean isSetImportance() {
    return this.importance != null;
  }

  public void setImportanceIsSet(boolean value) {
    if (!value) {
      this.importance = null;
    }
  }

  /**
   * 
   * @see LocationScope
   */
  @org.apache.thrift.annotation.Nullable
  public LocationScope getScope() {
    return this.scope;
  }

  /**
   * 
   * @see LocationScope
   */
  public LocationFilter setScope(@org.apache.thrift.annotation.Nullable LocationScope scope) {
    this.scope = scope;
    return this;
  }

  public void unsetScope() {
    this.scope = null;
  }

  /** Returns true if field scope is set (has been assigned a value) and false otherwise */
  public boolean isSetScope() {
    return this.scope != null;
  }

  public void setScopeIsSet(boolean value) {
    if (!value) {
      this.scope = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getCountryCode() {
    return this.countryCode;
  }

  public LocationFilter setCountryCode(@org.apache.thrift.annotation.Nullable java.lang.String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

  public void unsetCountryCode() {
    this.countryCode = null;
  }

  /** Returns true if field countryCode is set (has been assigned a value) and false otherwise */
  public boolean isSetCountryCode() {
    return this.countryCode != null;
  }

  public void setCountryCodeIsSet(boolean value) {
    if (!value) {
      this.countryCode = null;
    }
  }

  /**
   * 
   * @see DistanceUnit
   */
  @org.apache.thrift.annotation.Nullable
  public DistanceUnit getDistanceUnit() {
    return this.distanceUnit;
  }

  /**
   * 
   * @see DistanceUnit
   */
  public LocationFilter setDistanceUnit(@org.apache.thrift.annotation.Nullable DistanceUnit distanceUnit) {
    this.distanceUnit = distanceUnit;
    return this;
  }

  public void unsetDistanceUnit() {
    this.distanceUnit = null;
  }

  /** Returns true if field distanceUnit is set (has been assigned a value) and false otherwise */
  public boolean isSetDistanceUnit() {
    return this.distanceUnit != null;
  }

  public void setDistanceUnitIsSet(boolean value) {
    if (!value) {
      this.distanceUnit = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case LAT:
      if (value == null) {
        unsetLat();
      } else {
        setLat((java.lang.Double)value);
      }
      break;

    case LON:
      if (value == null) {
        unsetLon();
      } else {
        setLon((java.lang.Double)value);
      }
      break;

    case RADIUS_KM:
      if (value == null) {
        unsetRadiusKm();
      } else {
        setRadiusKm((java.lang.Double)value);
      }
      break;

    case IMPORTANCE:
      if (value == null) {
        unsetImportance();
      } else {
        setImportance((Importance)value);
      }
      break;

    case SCOPE:
      if (value == null) {
        unsetScope();
      } else {
        setScope((LocationScope)value);
      }
      break;

    case COUNTRY_CODE:
      if (value == null) {
        unsetCountryCode();
      } else {
        setCountryCode((java.lang.String)value);
      }
      break;

    case DISTANCE_UNIT:
      if (value == null) {
        unsetDistanceUnit();
      } else {
        setDistanceUnit((DistanceUnit)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case LAT:
      return getLat();

    case LON:
      return getLon();

    case RADIUS_KM:
      return getRadiusKm();

    case IMPORTANCE:
      return getImportance();

    case SCOPE:
      return getScope();

    case COUNTRY_CODE:
      return getCountryCode();

    case DISTANCE_UNIT:
      return getDistanceUnit();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case LAT:
      return isSetLat();
    case LON:
      return isSetLon();
    case RADIUS_KM:
      return isSetRadiusKm();
    case IMPORTANCE:
      return isSetImportance();
    case SCOPE:
      return isSetScope();
    case COUNTRY_CODE:
      return isSetCountryCode();
    case DISTANCE_UNIT:
      return isSetDistanceUnit();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof LocationFilter)
      return this.equals((LocationFilter)that);
    return false;
  }

  public boolean equals(LocationFilter that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_lat = true;
    boolean that_present_lat = true;
    if (this_present_lat || that_present_lat) {
      if (!(this_present_lat && that_present_lat))
        return false;
      if (this.lat != that.lat)
        return false;
    }

    boolean this_present_lon = true;
    boolean that_present_lon = true;
    if (this_present_lon || that_present_lon) {
      if (!(this_present_lon && that_present_lon))
        return false;
      if (this.lon != that.lon)
        return false;
    }

    boolean this_present_radiusKm = true;
    boolean that_present_radiusKm = true;
    if (this_present_radiusKm || that_present_radiusKm) {
      if (!(this_present_radiusKm && that_present_radiusKm))
        return false;
      if (this.radiusKm != that.radiusKm)
        return false;
    }

    boolean this_present_importance = true && this.isSetImportance();
    boolean that_present_importance = true && that.isSetImportance();
    if (this_present_importance || that_present_importance) {
      if (!(this_present_importance && that_present_importance))
        return false;
      if (!this.importance.equals(that.importance))
        return false;
    }

    boolean this_present_scope = true && this.isSetScope();
    boolean that_present_scope = true && that.isSetScope();
    if (this_present_scope || that_present_scope) {
      if (!(this_present_scope && that_present_scope))
        return false;
      if (!this.scope.equals(that.scope))
        return false;
    }

    boolean this_present_countryCode = true && this.isSetCountryCode();
    boolean that_present_countryCode = true && that.isSetCountryCode();
    if (this_present_countryCode || that_present_countryCode) {
      if (!(this_present_countryCode && that_present_countryCode))
        return false;
      if (!this.countryCode.equals(that.countryCode))
        return false;
    }

    boolean this_present_distanceUnit = true && this.isSetDistanceUnit();
    boolean that_present_distanceUnit = true && that.isSetDistanceUnit();
    if (this_present_distanceUnit || that_present_distanceUnit) {
      if (!(this_present_distanceUnit && that_present_distanceUnit))
        return false;
      if (!this.distanceUnit.equals(that.distanceUnit))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(lat);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(lon);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(radiusKm);

    hashCode = hashCode * 8191 + ((isSetImportance()) ? 131071 : 524287);
    if (isSetImportance())
      hashCode = hashCode * 8191 + importance.getValue();

    hashCode = hashCode * 8191 + ((isSetScope()) ? 131071 : 524287);
    if (isSetScope())
      hashCode = hashCode * 8191 + scope.getValue();

    hashCode = hashCode * 8191 + ((isSetCountryCode()) ? 131071 : 524287);
    if (isSetCountryCode())
      hashCode = hashCode * 8191 + countryCode.hashCode();

    hashCode = hashCode * 8191 + ((isSetDistanceUnit()) ? 131071 : 524287);
    if (isSetDistanceUnit())
      hashCode = hashCode * 8191 + distanceUnit.getValue();

    return hashCode;
  }

  @Override
  public int compareTo(LocationFilter other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetLat(), other.isSetLat());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLat()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lat, other.lat);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetLon(), other.isSetLon());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLon()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lon, other.lon);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetRadiusKm(), other.isSetRadiusKm());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRadiusKm()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.radiusKm, other.radiusKm);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetImportance(), other.isSetImportance());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetImportance()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.importance, other.importance);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetScope(), other.isSetScope());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetScope()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.scope, other.scope);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetCountryCode(), other.isSetCountryCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCountryCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.countryCode, other.countryCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetDistanceUnit(), other.isSetDistanceUnit());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDistanceUnit()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.distanceUnit, other.distanceUnit);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("LocationFilter(");
    boolean first = true;

    sb.append("lat:");
    sb.append(this.lat);
    first = false;
    if (!first) sb.append(", ");
    sb.append("lon:");
    sb.append(this.lon);
    first = false;
    if (!first) sb.append(", ");
    sb.append("radiusKm:");
    sb.append(this.radiusKm);
    first = false;
    if (isSetImportance()) {
      if (!first) sb.append(", ");
      sb.append("importance:");
      if (this.importance == null) {
        sb.append("null");
      } else {
        sb.append(this.importance);
      }
      first = false;
    }
    if (isSetScope()) {
      if (!first) sb.append(", ");
      sb.append("scope:");
      if (this.scope == null) {
        sb.append("null");
      } else {
        sb.append(this.scope);
      }
      first = false;
    }
    if (isSetCountryCode()) {
      if (!first) sb.append(", ");
      sb.append("countryCode:");
      if (this.countryCode == null) {
        sb.append("null");
      } else {
        sb.append(this.countryCode);
      }
      first = false;
    }
    if (isSetDistanceUnit()) {
      if (!first) sb.append(", ");
      sb.append("distanceUnit:");
      if (this.distanceUnit == null) {
        sb.append("null");
      } else {
        sb.append(this.distanceUnit);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'lat' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'lon' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'radiusKm' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class LocationFilterStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public LocationFilterStandardScheme getScheme() {
      return new LocationFilterStandardScheme();
    }
  }

  private static class LocationFilterStandardScheme extends org.apache.thrift.scheme.StandardScheme<LocationFilter> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, LocationFilter struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // LAT
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.lat = iprot.readDouble();
              struct.setLatIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // LON
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.lon = iprot.readDouble();
              struct.setLonIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // RADIUS_KM
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.radiusKm = iprot.readDouble();
              struct.setRadiusKmIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // IMPORTANCE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.importance = now.calypso.backend.data.Importance.findByValue(iprot.readI32());
              struct.setImportanceIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // SCOPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.scope = now.calypso.backend.data.LocationScope.findByValue(iprot.readI32());
              struct.setScopeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // COUNTRY_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.countryCode = iprot.readString();
              struct.setCountryCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // DISTANCE_UNIT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.distanceUnit = now.calypso.backend.data.DistanceUnit.findByValue(iprot.readI32());
              struct.setDistanceUnitIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetLat()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'lat' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetLon()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'lon' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetRadiusKm()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'radiusKm' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, LocationFilter struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(LAT_FIELD_DESC);
      oprot.writeDouble(struct.lat);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(LON_FIELD_DESC);
      oprot.writeDouble(struct.lon);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(RADIUS_KM_FIELD_DESC);
      oprot.writeDouble(struct.radiusKm);
      oprot.writeFieldEnd();
      if (struct.importance != null) {
        if (struct.isSetImportance()) {
          oprot.writeFieldBegin(IMPORTANCE_FIELD_DESC);
          oprot.writeI32(struct.importance.getValue());
          oprot.writeFieldEnd();
        }
      }
      if (struct.scope != null) {
        if (struct.isSetScope()) {
          oprot.writeFieldBegin(SCOPE_FIELD_DESC);
          oprot.writeI32(struct.scope.getValue());
          oprot.writeFieldEnd();
        }
      }
      if (struct.countryCode != null) {
        if (struct.isSetCountryCode()) {
          oprot.writeFieldBegin(COUNTRY_CODE_FIELD_DESC);
          oprot.writeString(struct.countryCode);
          oprot.writeFieldEnd();
        }
      }
      if (struct.distanceUnit != null) {
        if (struct.isSetDistanceUnit()) {
          oprot.writeFieldBegin(DISTANCE_UNIT_FIELD_DESC);
          oprot.writeI32(struct.distanceUnit.getValue());
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class LocationFilterTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public LocationFilterTupleScheme getScheme() {
      return new LocationFilterTupleScheme();
    }
  }

  private static class LocationFilterTupleScheme extends org.apache.thrift.scheme.TupleScheme<LocationFilter> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, LocationFilter struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeDouble(struct.lat);
      oprot.writeDouble(struct.lon);
      oprot.writeDouble(struct.radiusKm);
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetImportance()) {
        optionals.set(0);
      }
      if (struct.isSetScope()) {
        optionals.set(1);
      }
      if (struct.isSetCountryCode()) {
        optionals.set(2);
      }
      if (struct.isSetDistanceUnit()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetImportance()) {
        oprot.writeI32(struct.importance.getValue());
      }
      if (struct.isSetScope()) {
        oprot.writeI32(struct.scope.getValue());
      }
      if (struct.isSetCountryCode()) {
        oprot.writeString(struct.countryCode);
      }
      if (struct.isSetDistanceUnit()) {
        oprot.writeI32(struct.distanceUnit.getValue());
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, LocationFilter struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.lat = iprot.readDouble();
      struct.setLatIsSet(true);
      struct.lon = iprot.readDouble();
      struct.setLonIsSet(true);
      struct.radiusKm = iprot.readDouble();
      struct.setRadiusKmIsSet(true);
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.importance = now.calypso.backend.data.Importance.findByValue(iprot.readI32());
        struct.setImportanceIsSet(true);
      }
      if (incoming.get(1)) {
        struct.scope = now.calypso.backend.data.LocationScope.findByValue(iprot.readI32());
        struct.setScopeIsSet(true);
      }
      if (incoming.get(2)) {
        struct.countryCode = iprot.readString();
        struct.setCountryCodeIsSet(true);
      }
      if (incoming.get(3)) {
        struct.distanceUnit = now.calypso.backend.data.DistanceUnit.findByValue(iprot.readI32());
        struct.setDistanceUnitIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

