/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package now.calypso.backend.data;


public enum LocationScope implements org.apache.thrift.TEnum {
  NEARBY(1),
  COUNTRY(2),
  WORLDWIDE(3);

  private final int value;

  private LocationScope(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static LocationScope findByValue(int value) { 
    switch (value) {
      case 1:
        return NEARBY;
      case 2:
        return COUNTRY;
      case 3:
        return WORLDWIDE;
      default:
        return null;
    }
  }
}
