/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package now.calypso.backend.data;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class ManyToManyFilter implements org.apache.thrift.TBase<ManyToManyFilter, ManyToManyFilter._Fields>, java.io.Serializable, Cloneable, Comparable<ManyToManyFilter> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ManyToManyFilter");

  private static final org.apache.thrift.protocol.TField SELF_FIELD_DESC = new org.apache.thrift.protocol.TField("self", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField MUST_HAVE_FIELD_DESC = new org.apache.thrift.protocol.TField("mustHave", org.apache.thrift.protocol.TType.LIST, (short)2);
  private static final org.apache.thrift.protocol.TField NICE_TO_HAVE_FIELD_DESC = new org.apache.thrift.protocol.TField("niceToHave", org.apache.thrift.protocol.TType.LIST, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ManyToManyFilterStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ManyToManyFilterTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> self; // optional
  public @org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> mustHave; // optional
  public @org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> niceToHave; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SELF((short)1, "self"),
    MUST_HAVE((short)2, "mustHave"),
    NICE_TO_HAVE((short)3, "niceToHave");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SELF
          return SELF;
        case 2: // MUST_HAVE
          return MUST_HAVE;
        case 3: // NICE_TO_HAVE
          return NICE_TO_HAVE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.SELF,_Fields.MUST_HAVE,_Fields.NICE_TO_HAVE};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SELF, new org.apache.thrift.meta_data.FieldMetaData("self", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.MUST_HAVE, new org.apache.thrift.meta_data.FieldMetaData("mustHave", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.NICE_TO_HAVE, new org.apache.thrift.meta_data.FieldMetaData("niceToHave", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ManyToManyFilter.class, metaDataMap);
  }

  public ManyToManyFilter() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ManyToManyFilter(ManyToManyFilter other) {
    if (other.isSetSelf()) {
      java.util.List<java.lang.String> __this__self = new java.util.ArrayList<java.lang.String>(other.self);
      this.self = __this__self;
    }
    if (other.isSetMustHave()) {
      java.util.List<java.lang.String> __this__mustHave = new java.util.ArrayList<java.lang.String>(other.mustHave);
      this.mustHave = __this__mustHave;
    }
    if (other.isSetNiceToHave()) {
      java.util.List<java.lang.String> __this__niceToHave = new java.util.ArrayList<java.lang.String>(other.niceToHave);
      this.niceToHave = __this__niceToHave;
    }
  }

  @Override
  public ManyToManyFilter deepCopy() {
    return new ManyToManyFilter(this);
  }

  @Override
  public void clear() {
    this.self = null;
    this.mustHave = null;
    this.niceToHave = null;
  }

  public int getSelfSize() {
    return (this.self == null) ? 0 : this.self.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.lang.String> getSelfIterator() {
    return (this.self == null) ? null : this.self.iterator();
  }

  public void addToSelf(java.lang.String elem) {
    if (this.self == null) {
      this.self = new java.util.ArrayList<java.lang.String>();
    }
    this.self.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<java.lang.String> getSelf() {
    return this.self;
  }

  public ManyToManyFilter setSelf(@org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> self) {
    this.self = self;
    return this;
  }

  public void unsetSelf() {
    this.self = null;
  }

  /** Returns true if field self is set (has been assigned a value) and false otherwise */
  public boolean isSetSelf() {
    return this.self != null;
  }

  public void setSelfIsSet(boolean value) {
    if (!value) {
      this.self = null;
    }
  }

  public int getMustHaveSize() {
    return (this.mustHave == null) ? 0 : this.mustHave.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.lang.String> getMustHaveIterator() {
    return (this.mustHave == null) ? null : this.mustHave.iterator();
  }

  public void addToMustHave(java.lang.String elem) {
    if (this.mustHave == null) {
      this.mustHave = new java.util.ArrayList<java.lang.String>();
    }
    this.mustHave.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<java.lang.String> getMustHave() {
    return this.mustHave;
  }

  public ManyToManyFilter setMustHave(@org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> mustHave) {
    this.mustHave = mustHave;
    return this;
  }

  public void unsetMustHave() {
    this.mustHave = null;
  }

  /** Returns true if field mustHave is set (has been assigned a value) and false otherwise */
  public boolean isSetMustHave() {
    return this.mustHave != null;
  }

  public void setMustHaveIsSet(boolean value) {
    if (!value) {
      this.mustHave = null;
    }
  }

  public int getNiceToHaveSize() {
    return (this.niceToHave == null) ? 0 : this.niceToHave.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.lang.String> getNiceToHaveIterator() {
    return (this.niceToHave == null) ? null : this.niceToHave.iterator();
  }

  public void addToNiceToHave(java.lang.String elem) {
    if (this.niceToHave == null) {
      this.niceToHave = new java.util.ArrayList<java.lang.String>();
    }
    this.niceToHave.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<java.lang.String> getNiceToHave() {
    return this.niceToHave;
  }

  public ManyToManyFilter setNiceToHave(@org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> niceToHave) {
    this.niceToHave = niceToHave;
    return this;
  }

  public void unsetNiceToHave() {
    this.niceToHave = null;
  }

  /** Returns true if field niceToHave is set (has been assigned a value) and false otherwise */
  public boolean isSetNiceToHave() {
    return this.niceToHave != null;
  }

  public void setNiceToHaveIsSet(boolean value) {
    if (!value) {
      this.niceToHave = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case SELF:
      if (value == null) {
        unsetSelf();
      } else {
        setSelf((java.util.List<java.lang.String>)value);
      }
      break;

    case MUST_HAVE:
      if (value == null) {
        unsetMustHave();
      } else {
        setMustHave((java.util.List<java.lang.String>)value);
      }
      break;

    case NICE_TO_HAVE:
      if (value == null) {
        unsetNiceToHave();
      } else {
        setNiceToHave((java.util.List<java.lang.String>)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case SELF:
      return getSelf();

    case MUST_HAVE:
      return getMustHave();

    case NICE_TO_HAVE:
      return getNiceToHave();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case SELF:
      return isSetSelf();
    case MUST_HAVE:
      return isSetMustHave();
    case NICE_TO_HAVE:
      return isSetNiceToHave();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof ManyToManyFilter)
      return this.equals((ManyToManyFilter)that);
    return false;
  }

  public boolean equals(ManyToManyFilter that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_self = true && this.isSetSelf();
    boolean that_present_self = true && that.isSetSelf();
    if (this_present_self || that_present_self) {
      if (!(this_present_self && that_present_self))
        return false;
      if (!this.self.equals(that.self))
        return false;
    }

    boolean this_present_mustHave = true && this.isSetMustHave();
    boolean that_present_mustHave = true && that.isSetMustHave();
    if (this_present_mustHave || that_present_mustHave) {
      if (!(this_present_mustHave && that_present_mustHave))
        return false;
      if (!this.mustHave.equals(that.mustHave))
        return false;
    }

    boolean this_present_niceToHave = true && this.isSetNiceToHave();
    boolean that_present_niceToHave = true && that.isSetNiceToHave();
    if (this_present_niceToHave || that_present_niceToHave) {
      if (!(this_present_niceToHave && that_present_niceToHave))
        return false;
      if (!this.niceToHave.equals(that.niceToHave))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetSelf()) ? 131071 : 524287);
    if (isSetSelf())
      hashCode = hashCode * 8191 + self.hashCode();

    hashCode = hashCode * 8191 + ((isSetMustHave()) ? 131071 : 524287);
    if (isSetMustHave())
      hashCode = hashCode * 8191 + mustHave.hashCode();

    hashCode = hashCode * 8191 + ((isSetNiceToHave()) ? 131071 : 524287);
    if (isSetNiceToHave())
      hashCode = hashCode * 8191 + niceToHave.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(ManyToManyFilter other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetSelf(), other.isSetSelf());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSelf()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.self, other.self);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetMustHave(), other.isSetMustHave());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMustHave()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mustHave, other.mustHave);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetNiceToHave(), other.isSetNiceToHave());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNiceToHave()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.niceToHave, other.niceToHave);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("ManyToManyFilter(");
    boolean first = true;

    if (isSetSelf()) {
      sb.append("self:");
      if (this.self == null) {
        sb.append("null");
      } else {
        sb.append(this.self);
      }
      first = false;
    }
    if (isSetMustHave()) {
      if (!first) sb.append(", ");
      sb.append("mustHave:");
      if (this.mustHave == null) {
        sb.append("null");
      } else {
        sb.append(this.mustHave);
      }
      first = false;
    }
    if (isSetNiceToHave()) {
      if (!first) sb.append(", ");
      sb.append("niceToHave:");
      if (this.niceToHave == null) {
        sb.append("null");
      } else {
        sb.append(this.niceToHave);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ManyToManyFilterStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public ManyToManyFilterStandardScheme getScheme() {
      return new ManyToManyFilterStandardScheme();
    }
  }

  private static class ManyToManyFilterStandardScheme extends org.apache.thrift.scheme.StandardScheme<ManyToManyFilter> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, ManyToManyFilter struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SELF
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                struct.self = new java.util.ArrayList<java.lang.String>(_list8.size);
                @org.apache.thrift.annotation.Nullable java.lang.String _elem9;
                for (int _i10 = 0; _i10 < _list8.size; ++_i10)
                {
                  _elem9 = iprot.readString();
                  struct.self.add(_elem9);
                }
                iprot.readListEnd();
              }
              struct.setSelfIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // MUST_HAVE
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list11 = iprot.readListBegin();
                struct.mustHave = new java.util.ArrayList<java.lang.String>(_list11.size);
                @org.apache.thrift.annotation.Nullable java.lang.String _elem12;
                for (int _i13 = 0; _i13 < _list11.size; ++_i13)
                {
                  _elem12 = iprot.readString();
                  struct.mustHave.add(_elem12);
                }
                iprot.readListEnd();
              }
              struct.setMustHaveIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // NICE_TO_HAVE
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list14 = iprot.readListBegin();
                struct.niceToHave = new java.util.ArrayList<java.lang.String>(_list14.size);
                @org.apache.thrift.annotation.Nullable java.lang.String _elem15;
                for (int _i16 = 0; _i16 < _list14.size; ++_i16)
                {
                  _elem15 = iprot.readString();
                  struct.niceToHave.add(_elem15);
                }
                iprot.readListEnd();
              }
              struct.setNiceToHaveIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, ManyToManyFilter struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.self != null) {
        if (struct.isSetSelf()) {
          oprot.writeFieldBegin(SELF_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.self.size()));
            for (java.lang.String _iter17 : struct.self)
            {
              oprot.writeString(_iter17);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.mustHave != null) {
        if (struct.isSetMustHave()) {
          oprot.writeFieldBegin(MUST_HAVE_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.mustHave.size()));
            for (java.lang.String _iter18 : struct.mustHave)
            {
              oprot.writeString(_iter18);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.niceToHave != null) {
        if (struct.isSetNiceToHave()) {
          oprot.writeFieldBegin(NICE_TO_HAVE_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.niceToHave.size()));
            for (java.lang.String _iter19 : struct.niceToHave)
            {
              oprot.writeString(_iter19);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ManyToManyFilterTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public ManyToManyFilterTupleScheme getScheme() {
      return new ManyToManyFilterTupleScheme();
    }
  }

  private static class ManyToManyFilterTupleScheme extends org.apache.thrift.scheme.TupleScheme<ManyToManyFilter> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ManyToManyFilter struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetSelf()) {
        optionals.set(0);
      }
      if (struct.isSetMustHave()) {
        optionals.set(1);
      }
      if (struct.isSetNiceToHave()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetSelf()) {
        {
          oprot.writeI32(struct.self.size());
          for (java.lang.String _iter20 : struct.self)
          {
            oprot.writeString(_iter20);
          }
        }
      }
      if (struct.isSetMustHave()) {
        {
          oprot.writeI32(struct.mustHave.size());
          for (java.lang.String _iter21 : struct.mustHave)
          {
            oprot.writeString(_iter21);
          }
        }
      }
      if (struct.isSetNiceToHave()) {
        {
          oprot.writeI32(struct.niceToHave.size());
          for (java.lang.String _iter22 : struct.niceToHave)
          {
            oprot.writeString(_iter22);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ManyToManyFilter struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list23 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRING);
          struct.self = new java.util.ArrayList<java.lang.String>(_list23.size);
          @org.apache.thrift.annotation.Nullable java.lang.String _elem24;
          for (int _i25 = 0; _i25 < _list23.size; ++_i25)
          {
            _elem24 = iprot.readString();
            struct.self.add(_elem24);
          }
        }
        struct.setSelfIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list26 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRING);
          struct.mustHave = new java.util.ArrayList<java.lang.String>(_list26.size);
          @org.apache.thrift.annotation.Nullable java.lang.String _elem27;
          for (int _i28 = 0; _i28 < _list26.size; ++_i28)
          {
            _elem27 = iprot.readString();
            struct.mustHave.add(_elem27);
          }
        }
        struct.setMustHaveIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TList _list29 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRING);
          struct.niceToHave = new java.util.ArrayList<java.lang.String>(_list29.size);
          @org.apache.thrift.annotation.Nullable java.lang.String _elem30;
          for (int _i31 = 0; _i31 < _list29.size; ++_i31)
          {
            _elem30 = iprot.readString();
            struct.niceToHave.add(_elem30);
          }
        }
        struct.setNiceToHaveIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

