/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package now.calypso.backend.data;


public enum MatchStandardQuestionAnswerType implements org.apache.thrift.TEnum {
  SINGLE_CHOICE(1),
  MULTI_CHOICE(2);

  private final int value;

  private MatchStandardQuestionAnswerType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static MatchStandardQuestionAnswerType findByValue(int value) { 
    switch (value) {
      case 1:
        return SINGLE_CHOICE;
      case 2:
        return MULTI_CHOICE;
      default:
        return null;
    }
  }
}
