/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package now.calypso.backend.data;


public enum PrivatePromptStatus implements org.apache.thrift.TEnum {
  ACTIVE(1),
  ANSWERED(2),
  SKIPPED(3),
  SNOOZED(4);

  private final int value;

  private PrivatePromptStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static PrivatePromptStatus findByValue(int value) { 
    switch (value) {
      case 1:
        return ACTIVE;
      case 2:
        return ANSWERED;
      case 3:
        return SKIPPED;
      case 4:
        return SNOOZED;
      default:
        return null;
    }
  }
}
