/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package now.calypso.backend.data;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class PromptResponse implements org.apache.thrift.TBase<PromptResponse, PromptResponse._Fields>, java.io.Serializable, Cloneable, Comparable<PromptResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PromptResponse");

  private static final org.apache.thrift.protocol.TField RESPONSE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("responseId", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField ACCOUNT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("accountId", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField QUESTION_FIELD_DESC = new org.apache.thrift.protocol.TField("question", org.apache.thrift.protocol.TType.STRUCT, (short)3);
  private static final org.apache.thrift.protocol.TField REACTION_FIELD_DESC = new org.apache.thrift.protocol.TField("reaction", org.apache.thrift.protocol.TType.I32, (short)4);
  private static final org.apache.thrift.protocol.TField ANSWER_TEXT_FIELD_DESC = new org.apache.thrift.protocol.TField("answerText", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField ATTACHMENTS_FIELD_DESC = new org.apache.thrift.protocol.TField("attachments", org.apache.thrift.protocol.TType.LIST, (short)6);
  private static final org.apache.thrift.protocol.TField SERVED_AT_FIELD_DESC = new org.apache.thrift.protocol.TField("servedAt", org.apache.thrift.protocol.TType.I64, (short)7);
  private static final org.apache.thrift.protocol.TField ANSWERED_AT_FIELD_DESC = new org.apache.thrift.protocol.TField("answeredAt", org.apache.thrift.protocol.TType.I64, (short)8);
  private static final org.apache.thrift.protocol.TField RELATED_TARGET_ACCOUNT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("relatedTargetAccountId", org.apache.thrift.protocol.TType.I64, (short)9);
  private static final org.apache.thrift.protocol.TField COMMENT_FIELD_DESC = new org.apache.thrift.protocol.TField("comment", org.apache.thrift.protocol.TType.STRING, (short)10);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new PromptResponseStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new PromptResponseTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String responseId; // required
  public long accountId; // required
  public @org.apache.thrift.annotation.Nullable PromptQuestion question; // required
  /**
   * 
   * @see PromptReaction
   */
  public @org.apache.thrift.annotation.Nullable PromptReaction reaction; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String answerText; // optional
  public @org.apache.thrift.annotation.Nullable java.util.List<AttachmentWithId> attachments; // optional
  public long servedAt; // optional
  public long answeredAt; // optional
  public long relatedTargetAccountId; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String comment; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    RESPONSE_ID((short)1, "responseId"),
    ACCOUNT_ID((short)2, "accountId"),
    QUESTION((short)3, "question"),
    /**
     * 
     * @see PromptReaction
     */
    REACTION((short)4, "reaction"),
    ANSWER_TEXT((short)5, "answerText"),
    ATTACHMENTS((short)6, "attachments"),
    SERVED_AT((short)7, "servedAt"),
    ANSWERED_AT((short)8, "answeredAt"),
    RELATED_TARGET_ACCOUNT_ID((short)9, "relatedTargetAccountId"),
    COMMENT((short)10, "comment");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RESPONSE_ID
          return RESPONSE_ID;
        case 2: // ACCOUNT_ID
          return ACCOUNT_ID;
        case 3: // QUESTION
          return QUESTION;
        case 4: // REACTION
          return REACTION;
        case 5: // ANSWER_TEXT
          return ANSWER_TEXT;
        case 6: // ATTACHMENTS
          return ATTACHMENTS;
        case 7: // SERVED_AT
          return SERVED_AT;
        case 8: // ANSWERED_AT
          return ANSWERED_AT;
        case 9: // RELATED_TARGET_ACCOUNT_ID
          return RELATED_TARGET_ACCOUNT_ID;
        case 10: // COMMENT
          return COMMENT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ACCOUNTID_ISSET_ID = 0;
  private static final int __SERVEDAT_ISSET_ID = 1;
  private static final int __ANSWEREDAT_ISSET_ID = 2;
  private static final int __RELATEDTARGETACCOUNTID_ISSET_ID = 3;
  private byte __isset_bitfield = 0;
  private static final _Fields[] optionals = {_Fields.REACTION,_Fields.ANSWER_TEXT,_Fields.ATTACHMENTS,_Fields.SERVED_AT,_Fields.ANSWERED_AT,_Fields.RELATED_TARGET_ACCOUNT_ID,_Fields.COMMENT};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RESPONSE_ID, new org.apache.thrift.meta_data.FieldMetaData("responseId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ACCOUNT_ID, new org.apache.thrift.meta_data.FieldMetaData("accountId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "AccountId")));
    tmpMap.put(_Fields.QUESTION, new org.apache.thrift.meta_data.FieldMetaData("question", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, PromptQuestion.class)));
    tmpMap.put(_Fields.REACTION, new org.apache.thrift.meta_data.FieldMetaData("reaction", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, PromptReaction.class)));
    tmpMap.put(_Fields.ANSWER_TEXT, new org.apache.thrift.meta_data.FieldMetaData("answerText", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ATTACHMENTS, new org.apache.thrift.meta_data.FieldMetaData("attachments", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, AttachmentWithId.class))));
    tmpMap.put(_Fields.SERVED_AT, new org.apache.thrift.meta_data.FieldMetaData("servedAt", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "Timestamp")));
    tmpMap.put(_Fields.ANSWERED_AT, new org.apache.thrift.meta_data.FieldMetaData("answeredAt", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "Timestamp")));
    tmpMap.put(_Fields.RELATED_TARGET_ACCOUNT_ID, new org.apache.thrift.meta_data.FieldMetaData("relatedTargetAccountId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "AccountId")));
    tmpMap.put(_Fields.COMMENT, new org.apache.thrift.meta_data.FieldMetaData("comment", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PromptResponse.class, metaDataMap);
  }

  public PromptResponse() {
  }

  public PromptResponse(
    java.lang.String responseId,
    long accountId,
    PromptQuestion question)
  {
    this();
    this.responseId = responseId;
    this.accountId = accountId;
    setAccountIdIsSet(true);
    this.question = question;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PromptResponse(PromptResponse other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetResponseId()) {
      this.responseId = other.responseId;
    }
    this.accountId = other.accountId;
    if (other.isSetQuestion()) {
      this.question = new PromptQuestion(other.question);
    }
    if (other.isSetReaction()) {
      this.reaction = other.reaction;
    }
    if (other.isSetAnswerText()) {
      this.answerText = other.answerText;
    }
    if (other.isSetAttachments()) {
      java.util.List<AttachmentWithId> __this__attachments = new java.util.ArrayList<AttachmentWithId>(other.attachments.size());
      for (AttachmentWithId other_element : other.attachments) {
        __this__attachments.add(new AttachmentWithId(other_element));
      }
      this.attachments = __this__attachments;
    }
    this.servedAt = other.servedAt;
    this.answeredAt = other.answeredAt;
    this.relatedTargetAccountId = other.relatedTargetAccountId;
    if (other.isSetComment()) {
      this.comment = other.comment;
    }
  }

  @Override
  public PromptResponse deepCopy() {
    return new PromptResponse(this);
  }

  @Override
  public void clear() {
    this.responseId = null;
    setAccountIdIsSet(false);
    this.accountId = 0;
    this.question = null;
    this.reaction = null;
    this.answerText = null;
    this.attachments = null;
    setServedAtIsSet(false);
    this.servedAt = 0;
    setAnsweredAtIsSet(false);
    this.answeredAt = 0;
    setRelatedTargetAccountIdIsSet(false);
    this.relatedTargetAccountId = 0;
    this.comment = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getResponseId() {
    return this.responseId;
  }

  public PromptResponse setResponseId(@org.apache.thrift.annotation.Nullable java.lang.String responseId) {
    this.responseId = responseId;
    return this;
  }

  public void unsetResponseId() {
    this.responseId = null;
  }

  /** Returns true if field responseId is set (has been assigned a value) and false otherwise */
  public boolean isSetResponseId() {
    return this.responseId != null;
  }

  public void setResponseIdIsSet(boolean value) {
    if (!value) {
      this.responseId = null;
    }
  }

  public long getAccountId() {
    return this.accountId;
  }

  public PromptResponse setAccountId(long accountId) {
    this.accountId = accountId;
    setAccountIdIsSet(true);
    return this;
  }

  public void unsetAccountId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ACCOUNTID_ISSET_ID);
  }

  /** Returns true if field accountId is set (has been assigned a value) and false otherwise */
  public boolean isSetAccountId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ACCOUNTID_ISSET_ID);
  }

  public void setAccountIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ACCOUNTID_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public PromptQuestion getQuestion() {
    return this.question;
  }

  public PromptResponse setQuestion(@org.apache.thrift.annotation.Nullable PromptQuestion question) {
    this.question = question;
    return this;
  }

  public void unsetQuestion() {
    this.question = null;
  }

  /** Returns true if field question is set (has been assigned a value) and false otherwise */
  public boolean isSetQuestion() {
    return this.question != null;
  }

  public void setQuestionIsSet(boolean value) {
    if (!value) {
      this.question = null;
    }
  }

  /**
   * 
   * @see PromptReaction
   */
  @org.apache.thrift.annotation.Nullable
  public PromptReaction getReaction() {
    return this.reaction;
  }

  /**
   * 
   * @see PromptReaction
   */
  public PromptResponse setReaction(@org.apache.thrift.annotation.Nullable PromptReaction reaction) {
    this.reaction = reaction;
    return this;
  }

  public void unsetReaction() {
    this.reaction = null;
  }

  /** Returns true if field reaction is set (has been assigned a value) and false otherwise */
  public boolean isSetReaction() {
    return this.reaction != null;
  }

  public void setReactionIsSet(boolean value) {
    if (!value) {
      this.reaction = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getAnswerText() {
    return this.answerText;
  }

  public PromptResponse setAnswerText(@org.apache.thrift.annotation.Nullable java.lang.String answerText) {
    this.answerText = answerText;
    return this;
  }

  public void unsetAnswerText() {
    this.answerText = null;
  }

  /** Returns true if field answerText is set (has been assigned a value) and false otherwise */
  public boolean isSetAnswerText() {
    return this.answerText != null;
  }

  public void setAnswerTextIsSet(boolean value) {
    if (!value) {
      this.answerText = null;
    }
  }

  public int getAttachmentsSize() {
    return (this.attachments == null) ? 0 : this.attachments.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<AttachmentWithId> getAttachmentsIterator() {
    return (this.attachments == null) ? null : this.attachments.iterator();
  }

  public void addToAttachments(AttachmentWithId elem) {
    if (this.attachments == null) {
      this.attachments = new java.util.ArrayList<AttachmentWithId>();
    }
    this.attachments.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<AttachmentWithId> getAttachments() {
    return this.attachments;
  }

  public PromptResponse setAttachments(@org.apache.thrift.annotation.Nullable java.util.List<AttachmentWithId> attachments) {
    this.attachments = attachments;
    return this;
  }

  public void unsetAttachments() {
    this.attachments = null;
  }

  /** Returns true if field attachments is set (has been assigned a value) and false otherwise */
  public boolean isSetAttachments() {
    return this.attachments != null;
  }

  public void setAttachmentsIsSet(boolean value) {
    if (!value) {
      this.attachments = null;
    }
  }

  public long getServedAt() {
    return this.servedAt;
  }

  public PromptResponse setServedAt(long servedAt) {
    this.servedAt = servedAt;
    setServedAtIsSet(true);
    return this;
  }

  public void unsetServedAt() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SERVEDAT_ISSET_ID);
  }

  /** Returns true if field servedAt is set (has been assigned a value) and false otherwise */
  public boolean isSetServedAt() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SERVEDAT_ISSET_ID);
  }

  public void setServedAtIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SERVEDAT_ISSET_ID, value);
  }

  public long getAnsweredAt() {
    return this.answeredAt;
  }

  public PromptResponse setAnsweredAt(long answeredAt) {
    this.answeredAt = answeredAt;
    setAnsweredAtIsSet(true);
    return this;
  }

  public void unsetAnsweredAt() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ANSWEREDAT_ISSET_ID);
  }

  /** Returns true if field answeredAt is set (has been assigned a value) and false otherwise */
  public boolean isSetAnsweredAt() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ANSWEREDAT_ISSET_ID);
  }

  public void setAnsweredAtIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ANSWEREDAT_ISSET_ID, value);
  }

  public long getRelatedTargetAccountId() {
    return this.relatedTargetAccountId;
  }

  public PromptResponse setRelatedTargetAccountId(long relatedTargetAccountId) {
    this.relatedTargetAccountId = relatedTargetAccountId;
    setRelatedTargetAccountIdIsSet(true);
    return this;
  }

  public void unsetRelatedTargetAccountId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __RELATEDTARGETACCOUNTID_ISSET_ID);
  }

  /** Returns true if field relatedTargetAccountId is set (has been assigned a value) and false otherwise */
  public boolean isSetRelatedTargetAccountId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __RELATEDTARGETACCOUNTID_ISSET_ID);
  }

  public void setRelatedTargetAccountIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __RELATEDTARGETACCOUNTID_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getComment() {
    return this.comment;
  }

  public PromptResponse setComment(@org.apache.thrift.annotation.Nullable java.lang.String comment) {
    this.comment = comment;
    return this;
  }

  public void unsetComment() {
    this.comment = null;
  }

  /** Returns true if field comment is set (has been assigned a value) and false otherwise */
  public boolean isSetComment() {
    return this.comment != null;
  }

  public void setCommentIsSet(boolean value) {
    if (!value) {
      this.comment = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case RESPONSE_ID:
      if (value == null) {
        unsetResponseId();
      } else {
        setResponseId((java.lang.String)value);
      }
      break;

    case ACCOUNT_ID:
      if (value == null) {
        unsetAccountId();
      } else {
        setAccountId((java.lang.Long)value);
      }
      break;

    case QUESTION:
      if (value == null) {
        unsetQuestion();
      } else {
        setQuestion((PromptQuestion)value);
      }
      break;

    case REACTION:
      if (value == null) {
        unsetReaction();
      } else {
        setReaction((PromptReaction)value);
      }
      break;

    case ANSWER_TEXT:
      if (value == null) {
        unsetAnswerText();
      } else {
        setAnswerText((java.lang.String)value);
      }
      break;

    case ATTACHMENTS:
      if (value == null) {
        unsetAttachments();
      } else {
        setAttachments((java.util.List<AttachmentWithId>)value);
      }
      break;

    case SERVED_AT:
      if (value == null) {
        unsetServedAt();
      } else {
        setServedAt((java.lang.Long)value);
      }
      break;

    case ANSWERED_AT:
      if (value == null) {
        unsetAnsweredAt();
      } else {
        setAnsweredAt((java.lang.Long)value);
      }
      break;

    case RELATED_TARGET_ACCOUNT_ID:
      if (value == null) {
        unsetRelatedTargetAccountId();
      } else {
        setRelatedTargetAccountId((java.lang.Long)value);
      }
      break;

    case COMMENT:
      if (value == null) {
        unsetComment();
      } else {
        setComment((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case RESPONSE_ID:
      return getResponseId();

    case ACCOUNT_ID:
      return getAccountId();

    case QUESTION:
      return getQuestion();

    case REACTION:
      return getReaction();

    case ANSWER_TEXT:
      return getAnswerText();

    case ATTACHMENTS:
      return getAttachments();

    case SERVED_AT:
      return getServedAt();

    case ANSWERED_AT:
      return getAnsweredAt();

    case RELATED_TARGET_ACCOUNT_ID:
      return getRelatedTargetAccountId();

    case COMMENT:
      return getComment();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case RESPONSE_ID:
      return isSetResponseId();
    case ACCOUNT_ID:
      return isSetAccountId();
    case QUESTION:
      return isSetQuestion();
    case REACTION:
      return isSetReaction();
    case ANSWER_TEXT:
      return isSetAnswerText();
    case ATTACHMENTS:
      return isSetAttachments();
    case SERVED_AT:
      return isSetServedAt();
    case ANSWERED_AT:
      return isSetAnsweredAt();
    case RELATED_TARGET_ACCOUNT_ID:
      return isSetRelatedTargetAccountId();
    case COMMENT:
      return isSetComment();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof PromptResponse)
      return this.equals((PromptResponse)that);
    return false;
  }

  public boolean equals(PromptResponse that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_responseId = true && this.isSetResponseId();
    boolean that_present_responseId = true && that.isSetResponseId();
    if (this_present_responseId || that_present_responseId) {
      if (!(this_present_responseId && that_present_responseId))
        return false;
      if (!this.responseId.equals(that.responseId))
        return false;
    }

    boolean this_present_accountId = true;
    boolean that_present_accountId = true;
    if (this_present_accountId || that_present_accountId) {
      if (!(this_present_accountId && that_present_accountId))
        return false;
      if (this.accountId != that.accountId)
        return false;
    }

    boolean this_present_question = true && this.isSetQuestion();
    boolean that_present_question = true && that.isSetQuestion();
    if (this_present_question || that_present_question) {
      if (!(this_present_question && that_present_question))
        return false;
      if (!this.question.equals(that.question))
        return false;
    }

    boolean this_present_reaction = true && this.isSetReaction();
    boolean that_present_reaction = true && that.isSetReaction();
    if (this_present_reaction || that_present_reaction) {
      if (!(this_present_reaction && that_present_reaction))
        return false;
      if (!this.reaction.equals(that.reaction))
        return false;
    }

    boolean this_present_answerText = true && this.isSetAnswerText();
    boolean that_present_answerText = true && that.isSetAnswerText();
    if (this_present_answerText || that_present_answerText) {
      if (!(this_present_answerText && that_present_answerText))
        return false;
      if (!this.answerText.equals(that.answerText))
        return false;
    }

    boolean this_present_attachments = true && this.isSetAttachments();
    boolean that_present_attachments = true && that.isSetAttachments();
    if (this_present_attachments || that_present_attachments) {
      if (!(this_present_attachments && that_present_attachments))
        return false;
      if (!this.attachments.equals(that.attachments))
        return false;
    }

    boolean this_present_servedAt = true && this.isSetServedAt();
    boolean that_present_servedAt = true && that.isSetServedAt();
    if (this_present_servedAt || that_present_servedAt) {
      if (!(this_present_servedAt && that_present_servedAt))
        return false;
      if (this.servedAt != that.servedAt)
        return false;
    }

    boolean this_present_answeredAt = true && this.isSetAnsweredAt();
    boolean that_present_answeredAt = true && that.isSetAnsweredAt();
    if (this_present_answeredAt || that_present_answeredAt) {
      if (!(this_present_answeredAt && that_present_answeredAt))
        return false;
      if (this.answeredAt != that.answeredAt)
        return false;
    }

    boolean this_present_relatedTargetAccountId = true && this.isSetRelatedTargetAccountId();
    boolean that_present_relatedTargetAccountId = true && that.isSetRelatedTargetAccountId();
    if (this_present_relatedTargetAccountId || that_present_relatedTargetAccountId) {
      if (!(this_present_relatedTargetAccountId && that_present_relatedTargetAccountId))
        return false;
      if (this.relatedTargetAccountId != that.relatedTargetAccountId)
        return false;
    }

    boolean this_present_comment = true && this.isSetComment();
    boolean that_present_comment = true && that.isSetComment();
    if (this_present_comment || that_present_comment) {
      if (!(this_present_comment && that_present_comment))
        return false;
      if (!this.comment.equals(that.comment))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetResponseId()) ? 131071 : 524287);
    if (isSetResponseId())
      hashCode = hashCode * 8191 + responseId.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(accountId);

    hashCode = hashCode * 8191 + ((isSetQuestion()) ? 131071 : 524287);
    if (isSetQuestion())
      hashCode = hashCode * 8191 + question.hashCode();

    hashCode = hashCode * 8191 + ((isSetReaction()) ? 131071 : 524287);
    if (isSetReaction())
      hashCode = hashCode * 8191 + reaction.getValue();

    hashCode = hashCode * 8191 + ((isSetAnswerText()) ? 131071 : 524287);
    if (isSetAnswerText())
      hashCode = hashCode * 8191 + answerText.hashCode();

    hashCode = hashCode * 8191 + ((isSetAttachments()) ? 131071 : 524287);
    if (isSetAttachments())
      hashCode = hashCode * 8191 + attachments.hashCode();

    hashCode = hashCode * 8191 + ((isSetServedAt()) ? 131071 : 524287);
    if (isSetServedAt())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(servedAt);

    hashCode = hashCode * 8191 + ((isSetAnsweredAt()) ? 131071 : 524287);
    if (isSetAnsweredAt())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(answeredAt);

    hashCode = hashCode * 8191 + ((isSetRelatedTargetAccountId()) ? 131071 : 524287);
    if (isSetRelatedTargetAccountId())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(relatedTargetAccountId);

    hashCode = hashCode * 8191 + ((isSetComment()) ? 131071 : 524287);
    if (isSetComment())
      hashCode = hashCode * 8191 + comment.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(PromptResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetResponseId(), other.isSetResponseId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResponseId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.responseId, other.responseId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetAccountId(), other.isSetAccountId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAccountId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.accountId, other.accountId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetQuestion(), other.isSetQuestion());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetQuestion()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.question, other.question);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetReaction(), other.isSetReaction());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReaction()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.reaction, other.reaction);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetAnswerText(), other.isSetAnswerText());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAnswerText()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.answerText, other.answerText);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetAttachments(), other.isSetAttachments());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAttachments()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.attachments, other.attachments);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetServedAt(), other.isSetServedAt());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetServedAt()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.servedAt, other.servedAt);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetAnsweredAt(), other.isSetAnsweredAt());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAnsweredAt()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.answeredAt, other.answeredAt);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetRelatedTargetAccountId(), other.isSetRelatedTargetAccountId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRelatedTargetAccountId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.relatedTargetAccountId, other.relatedTargetAccountId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetComment(), other.isSetComment());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetComment()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.comment, other.comment);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("PromptResponse(");
    boolean first = true;

    sb.append("responseId:");
    if (this.responseId == null) {
      sb.append("null");
    } else {
      sb.append(this.responseId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("accountId:");
    sb.append(this.accountId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("question:");
    if (this.question == null) {
      sb.append("null");
    } else {
      sb.append(this.question);
    }
    first = false;
    if (isSetReaction()) {
      if (!first) sb.append(", ");
      sb.append("reaction:");
      if (this.reaction == null) {
        sb.append("null");
      } else {
        sb.append(this.reaction);
      }
      first = false;
    }
    if (isSetAnswerText()) {
      if (!first) sb.append(", ");
      sb.append("answerText:");
      if (this.answerText == null) {
        sb.append("null");
      } else {
        sb.append(this.answerText);
      }
      first = false;
    }
    if (isSetAttachments()) {
      if (!first) sb.append(", ");
      sb.append("attachments:");
      if (this.attachments == null) {
        sb.append("null");
      } else {
        sb.append(this.attachments);
      }
      first = false;
    }
    if (isSetServedAt()) {
      if (!first) sb.append(", ");
      sb.append("servedAt:");
      sb.append(this.servedAt);
      first = false;
    }
    if (isSetAnsweredAt()) {
      if (!first) sb.append(", ");
      sb.append("answeredAt:");
      sb.append(this.answeredAt);
      first = false;
    }
    if (isSetRelatedTargetAccountId()) {
      if (!first) sb.append(", ");
      sb.append("relatedTargetAccountId:");
      sb.append(this.relatedTargetAccountId);
      first = false;
    }
    if (isSetComment()) {
      if (!first) sb.append(", ");
      sb.append("comment:");
      if (this.comment == null) {
        sb.append("null");
      } else {
        sb.append(this.comment);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (responseId == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'responseId' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'accountId' because it's a primitive and you chose the non-beans generator.
    if (question == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'question' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
    if (question != null) {
      question.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PromptResponseStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public PromptResponseStandardScheme getScheme() {
      return new PromptResponseStandardScheme();
    }
  }

  private static class PromptResponseStandardScheme extends org.apache.thrift.scheme.StandardScheme<PromptResponse> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, PromptResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RESPONSE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.responseId = iprot.readString();
              struct.setResponseIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // ACCOUNT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.accountId = iprot.readI64();
              struct.setAccountIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // QUESTION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.question = new PromptQuestion();
              struct.question.read(iprot);
              struct.setQuestionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // REACTION
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.reaction = now.calypso.backend.data.PromptReaction.findByValue(iprot.readI32());
              struct.setReactionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // ANSWER_TEXT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.answerText = iprot.readString();
              struct.setAnswerTextIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // ATTACHMENTS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list40 = iprot.readListBegin();
                struct.attachments = new java.util.ArrayList<AttachmentWithId>(_list40.size);
                @org.apache.thrift.annotation.Nullable AttachmentWithId _elem41;
                for (int _i42 = 0; _i42 < _list40.size; ++_i42)
                {
                  _elem41 = new AttachmentWithId();
                  _elem41.read(iprot);
                  struct.attachments.add(_elem41);
                }
                iprot.readListEnd();
              }
              struct.setAttachmentsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // SERVED_AT
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.servedAt = iprot.readI64();
              struct.setServedAtIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // ANSWERED_AT
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.answeredAt = iprot.readI64();
              struct.setAnsweredAtIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // RELATED_TARGET_ACCOUNT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.relatedTargetAccountId = iprot.readI64();
              struct.setRelatedTargetAccountIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // COMMENT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.comment = iprot.readString();
              struct.setCommentIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetAccountId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'accountId' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, PromptResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.responseId != null) {
        oprot.writeFieldBegin(RESPONSE_ID_FIELD_DESC);
        oprot.writeString(struct.responseId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(ACCOUNT_ID_FIELD_DESC);
      oprot.writeI64(struct.accountId);
      oprot.writeFieldEnd();
      if (struct.question != null) {
        oprot.writeFieldBegin(QUESTION_FIELD_DESC);
        struct.question.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.reaction != null) {
        if (struct.isSetReaction()) {
          oprot.writeFieldBegin(REACTION_FIELD_DESC);
          oprot.writeI32(struct.reaction.getValue());
          oprot.writeFieldEnd();
        }
      }
      if (struct.answerText != null) {
        if (struct.isSetAnswerText()) {
          oprot.writeFieldBegin(ANSWER_TEXT_FIELD_DESC);
          oprot.writeString(struct.answerText);
          oprot.writeFieldEnd();
        }
      }
      if (struct.attachments != null) {
        if (struct.isSetAttachments()) {
          oprot.writeFieldBegin(ATTACHMENTS_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.attachments.size()));
            for (AttachmentWithId _iter43 : struct.attachments)
            {
              _iter43.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetServedAt()) {
        oprot.writeFieldBegin(SERVED_AT_FIELD_DESC);
        oprot.writeI64(struct.servedAt);
        oprot.writeFieldEnd();
      }
      if (struct.isSetAnsweredAt()) {
        oprot.writeFieldBegin(ANSWERED_AT_FIELD_DESC);
        oprot.writeI64(struct.answeredAt);
        oprot.writeFieldEnd();
      }
      if (struct.isSetRelatedTargetAccountId()) {
        oprot.writeFieldBegin(RELATED_TARGET_ACCOUNT_ID_FIELD_DESC);
        oprot.writeI64(struct.relatedTargetAccountId);
        oprot.writeFieldEnd();
      }
      if (struct.comment != null) {
        if (struct.isSetComment()) {
          oprot.writeFieldBegin(COMMENT_FIELD_DESC);
          oprot.writeString(struct.comment);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PromptResponseTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public PromptResponseTupleScheme getScheme() {
      return new PromptResponseTupleScheme();
    }
  }

  private static class PromptResponseTupleScheme extends org.apache.thrift.scheme.TupleScheme<PromptResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PromptResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.responseId);
      oprot.writeI64(struct.accountId);
      struct.question.write(oprot);
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetReaction()) {
        optionals.set(0);
      }
      if (struct.isSetAnswerText()) {
        optionals.set(1);
      }
      if (struct.isSetAttachments()) {
        optionals.set(2);
      }
      if (struct.isSetServedAt()) {
        optionals.set(3);
      }
      if (struct.isSetAnsweredAt()) {
        optionals.set(4);
      }
      if (struct.isSetRelatedTargetAccountId()) {
        optionals.set(5);
      }
      if (struct.isSetComment()) {
        optionals.set(6);
      }
      oprot.writeBitSet(optionals, 7);
      if (struct.isSetReaction()) {
        oprot.writeI32(struct.reaction.getValue());
      }
      if (struct.isSetAnswerText()) {
        oprot.writeString(struct.answerText);
      }
      if (struct.isSetAttachments()) {
        {
          oprot.writeI32(struct.attachments.size());
          for (AttachmentWithId _iter44 : struct.attachments)
          {
            _iter44.write(oprot);
          }
        }
      }
      if (struct.isSetServedAt()) {
        oprot.writeI64(struct.servedAt);
      }
      if (struct.isSetAnsweredAt()) {
        oprot.writeI64(struct.answeredAt);
      }
      if (struct.isSetRelatedTargetAccountId()) {
        oprot.writeI64(struct.relatedTargetAccountId);
      }
      if (struct.isSetComment()) {
        oprot.writeString(struct.comment);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PromptResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.responseId = iprot.readString();
      struct.setResponseIdIsSet(true);
      struct.accountId = iprot.readI64();
      struct.setAccountIdIsSet(true);
      struct.question = new PromptQuestion();
      struct.question.read(iprot);
      struct.setQuestionIsSet(true);
      java.util.BitSet incoming = iprot.readBitSet(7);
      if (incoming.get(0)) {
        struct.reaction = now.calypso.backend.data.PromptReaction.findByValue(iprot.readI32());
        struct.setReactionIsSet(true);
      }
      if (incoming.get(1)) {
        struct.answerText = iprot.readString();
        struct.setAnswerTextIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TList _list45 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
          struct.attachments = new java.util.ArrayList<AttachmentWithId>(_list45.size);
          @org.apache.thrift.annotation.Nullable AttachmentWithId _elem46;
          for (int _i47 = 0; _i47 < _list45.size; ++_i47)
          {
            _elem46 = new AttachmentWithId();
            _elem46.read(iprot);
            struct.attachments.add(_elem46);
          }
        }
        struct.setAttachmentsIsSet(true);
      }
      if (incoming.get(3)) {
        struct.servedAt = iprot.readI64();
        struct.setServedAtIsSet(true);
      }
      if (incoming.get(4)) {
        struct.answeredAt = iprot.readI64();
        struct.setAnsweredAtIsSet(true);
      }
      if (incoming.get(5)) {
        struct.relatedTargetAccountId = iprot.readI64();
        struct.setRelatedTargetAccountIdIsSet(true);
      }
      if (incoming.get(6)) {
        struct.comment = iprot.readString();
        struct.setCommentIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

