/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package now.calypso.backend.data;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class PromptQuestion implements org.apache.thrift.TBase<PromptQuestion, PromptQuestion._Fields>, java.io.Serializable, Cloneable, Comparable<PromptQuestion> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PromptQuestion");

  private static final org.apache.thrift.protocol.TField PROMPT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("promptId", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField QUESTION_FIELD_DESC = new org.apache.thrift.protocol.TField("question", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField TOPIC_FIELD_DESC = new org.apache.thrift.protocol.TField("topic", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField TAGS_FIELD_DESC = new org.apache.thrift.protocol.TField("tags", org.apache.thrift.protocol.TType.LIST, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new PromptQuestionStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new PromptQuestionTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String promptId; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String question; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String topic; // optional
  public @org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> tags; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PROMPT_ID((short)1, "promptId"),
    QUESTION((short)2, "question"),
    TOPIC((short)3, "topic"),
    TAGS((short)4, "tags");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PROMPT_ID
          return PROMPT_ID;
        case 2: // QUESTION
          return QUESTION;
        case 3: // TOPIC
          return TOPIC;
        case 4: // TAGS
          return TAGS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields[] optionals = {_Fields.TOPIC,_Fields.TAGS};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PROMPT_ID, new org.apache.thrift.meta_data.FieldMetaData("promptId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.QUESTION, new org.apache.thrift.meta_data.FieldMetaData("question", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TOPIC, new org.apache.thrift.meta_data.FieldMetaData("topic", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TAGS, new org.apache.thrift.meta_data.FieldMetaData("tags", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PromptQuestion.class, metaDataMap);
  }

  public PromptQuestion() {
  }

  public PromptQuestion(
    java.lang.String promptId,
    java.lang.String question)
  {
    this();
    this.promptId = promptId;
    this.question = question;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PromptQuestion(PromptQuestion other) {
    if (other.isSetPromptId()) {
      this.promptId = other.promptId;
    }
    if (other.isSetQuestion()) {
      this.question = other.question;
    }
    if (other.isSetTopic()) {
      this.topic = other.topic;
    }
    if (other.isSetTags()) {
      java.util.List<java.lang.String> __this__tags = new java.util.ArrayList<java.lang.String>(other.tags);
      this.tags = __this__tags;
    }
  }

  @Override
  public PromptQuestion deepCopy() {
    return new PromptQuestion(this);
  }

  @Override
  public void clear() {
    this.promptId = null;
    this.question = null;
    this.topic = null;
    this.tags = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getPromptId() {
    return this.promptId;
  }

  public PromptQuestion setPromptId(@org.apache.thrift.annotation.Nullable java.lang.String promptId) {
    this.promptId = promptId;
    return this;
  }

  public void unsetPromptId() {
    this.promptId = null;
  }

  /** Returns true if field promptId is set (has been assigned a value) and false otherwise */
  public boolean isSetPromptId() {
    return this.promptId != null;
  }

  public void setPromptIdIsSet(boolean value) {
    if (!value) {
      this.promptId = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getQuestion() {
    return this.question;
  }

  public PromptQuestion setQuestion(@org.apache.thrift.annotation.Nullable java.lang.String question) {
    this.question = question;
    return this;
  }

  public void unsetQuestion() {
    this.question = null;
  }

  /** Returns true if field question is set (has been assigned a value) and false otherwise */
  public boolean isSetQuestion() {
    return this.question != null;
  }

  public void setQuestionIsSet(boolean value) {
    if (!value) {
      this.question = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getTopic() {
    return this.topic;
  }

  public PromptQuestion setTopic(@org.apache.thrift.annotation.Nullable java.lang.String topic) {
    this.topic = topic;
    return this;
  }

  public void unsetTopic() {
    this.topic = null;
  }

  /** Returns true if field topic is set (has been assigned a value) and false otherwise */
  public boolean isSetTopic() {
    return this.topic != null;
  }

  public void setTopicIsSet(boolean value) {
    if (!value) {
      this.topic = null;
    }
  }

  public int getTagsSize() {
    return (this.tags == null) ? 0 : this.tags.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.lang.String> getTagsIterator() {
    return (this.tags == null) ? null : this.tags.iterator();
  }

  public void addToTags(java.lang.String elem) {
    if (this.tags == null) {
      this.tags = new java.util.ArrayList<java.lang.String>();
    }
    this.tags.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<java.lang.String> getTags() {
    return this.tags;
  }

  public PromptQuestion setTags(@org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> tags) {
    this.tags = tags;
    return this;
  }

  public void unsetTags() {
    this.tags = null;
  }

  /** Returns true if field tags is set (has been assigned a value) and false otherwise */
  public boolean isSetTags() {
    return this.tags != null;
  }

  public void setTagsIsSet(boolean value) {
    if (!value) {
      this.tags = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case PROMPT_ID:
      if (value == null) {
        unsetPromptId();
      } else {
        setPromptId((java.lang.String)value);
      }
      break;

    case QUESTION:
      if (value == null) {
        unsetQuestion();
      } else {
        setQuestion((java.lang.String)value);
      }
      break;

    case TOPIC:
      if (value == null) {
        unsetTopic();
      } else {
        setTopic((java.lang.String)value);
      }
      break;

    case TAGS:
      if (value == null) {
        unsetTags();
      } else {
        setTags((java.util.List<java.lang.String>)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case PROMPT_ID:
      return getPromptId();

    case QUESTION:
      return getQuestion();

    case TOPIC:
      return getTopic();

    case TAGS:
      return getTags();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case PROMPT_ID:
      return isSetPromptId();
    case QUESTION:
      return isSetQuestion();
    case TOPIC:
      return isSetTopic();
    case TAGS:
      return isSetTags();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof PromptQuestion)
      return this.equals((PromptQuestion)that);
    return false;
  }

  public boolean equals(PromptQuestion that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_promptId = true && this.isSetPromptId();
    boolean that_present_promptId = true && that.isSetPromptId();
    if (this_present_promptId || that_present_promptId) {
      if (!(this_present_promptId && that_present_promptId))
        return false;
      if (!this.promptId.equals(that.promptId))
        return false;
    }

    boolean this_present_question = true && this.isSetQuestion();
    boolean that_present_question = true && that.isSetQuestion();
    if (this_present_question || that_present_question) {
      if (!(this_present_question && that_present_question))
        return false;
      if (!this.question.equals(that.question))
        return false;
    }

    boolean this_present_topic = true && this.isSetTopic();
    boolean that_present_topic = true && that.isSetTopic();
    if (this_present_topic || that_present_topic) {
      if (!(this_present_topic && that_present_topic))
        return false;
      if (!this.topic.equals(that.topic))
        return false;
    }

    boolean this_present_tags = true && this.isSetTags();
    boolean that_present_tags = true && that.isSetTags();
    if (this_present_tags || that_present_tags) {
      if (!(this_present_tags && that_present_tags))
        return false;
      if (!this.tags.equals(that.tags))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetPromptId()) ? 131071 : 524287);
    if (isSetPromptId())
      hashCode = hashCode * 8191 + promptId.hashCode();

    hashCode = hashCode * 8191 + ((isSetQuestion()) ? 131071 : 524287);
    if (isSetQuestion())
      hashCode = hashCode * 8191 + question.hashCode();

    hashCode = hashCode * 8191 + ((isSetTopic()) ? 131071 : 524287);
    if (isSetTopic())
      hashCode = hashCode * 8191 + topic.hashCode();

    hashCode = hashCode * 8191 + ((isSetTags()) ? 131071 : 524287);
    if (isSetTags())
      hashCode = hashCode * 8191 + tags.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(PromptQuestion other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetPromptId(), other.isSetPromptId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPromptId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.promptId, other.promptId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetQuestion(), other.isSetQuestion());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetQuestion()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.question, other.question);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetTopic(), other.isSetTopic());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTopic()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.topic, other.topic);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetTags(), other.isSetTags());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTags()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tags, other.tags);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("PromptQuestion(");
    boolean first = true;

    sb.append("promptId:");
    if (this.promptId == null) {
      sb.append("null");
    } else {
      sb.append(this.promptId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("question:");
    if (this.question == null) {
      sb.append("null");
    } else {
      sb.append(this.question);
    }
    first = false;
    if (isSetTopic()) {
      if (!first) sb.append(", ");
      sb.append("topic:");
      if (this.topic == null) {
        sb.append("null");
      } else {
        sb.append(this.topic);
      }
      first = false;
    }
    if (isSetTags()) {
      if (!first) sb.append(", ");
      sb.append("tags:");
      if (this.tags == null) {
        sb.append("null");
      } else {
        sb.append(this.tags);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (promptId == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'promptId' was not present! Struct: " + toString());
    }
    if (question == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'question' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PromptQuestionStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public PromptQuestionStandardScheme getScheme() {
      return new PromptQuestionStandardScheme();
    }
  }

  private static class PromptQuestionStandardScheme extends org.apache.thrift.scheme.StandardScheme<PromptQuestion> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, PromptQuestion struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PROMPT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.promptId = iprot.readString();
              struct.setPromptIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // QUESTION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.question = iprot.readString();
              struct.setQuestionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // TOPIC
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.topic = iprot.readString();
              struct.setTopicIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // TAGS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list32 = iprot.readListBegin();
                struct.tags = new java.util.ArrayList<java.lang.String>(_list32.size);
                @org.apache.thrift.annotation.Nullable java.lang.String _elem33;
                for (int _i34 = 0; _i34 < _list32.size; ++_i34)
                {
                  _elem33 = iprot.readString();
                  struct.tags.add(_elem33);
                }
                iprot.readListEnd();
              }
              struct.setTagsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, PromptQuestion struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.promptId != null) {
        oprot.writeFieldBegin(PROMPT_ID_FIELD_DESC);
        oprot.writeString(struct.promptId);
        oprot.writeFieldEnd();
      }
      if (struct.question != null) {
        oprot.writeFieldBegin(QUESTION_FIELD_DESC);
        oprot.writeString(struct.question);
        oprot.writeFieldEnd();
      }
      if (struct.topic != null) {
        if (struct.isSetTopic()) {
          oprot.writeFieldBegin(TOPIC_FIELD_DESC);
          oprot.writeString(struct.topic);
          oprot.writeFieldEnd();
        }
      }
      if (struct.tags != null) {
        if (struct.isSetTags()) {
          oprot.writeFieldBegin(TAGS_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.tags.size()));
            for (java.lang.String _iter35 : struct.tags)
            {
              oprot.writeString(_iter35);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PromptQuestionTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public PromptQuestionTupleScheme getScheme() {
      return new PromptQuestionTupleScheme();
    }
  }

  private static class PromptQuestionTupleScheme extends org.apache.thrift.scheme.TupleScheme<PromptQuestion> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PromptQuestion struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.promptId);
      oprot.writeString(struct.question);
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetTopic()) {
        optionals.set(0);
      }
      if (struct.isSetTags()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetTopic()) {
        oprot.writeString(struct.topic);
      }
      if (struct.isSetTags()) {
        {
          oprot.writeI32(struct.tags.size());
          for (java.lang.String _iter36 : struct.tags)
          {
            oprot.writeString(_iter36);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PromptQuestion struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.promptId = iprot.readString();
      struct.setPromptIdIsSet(true);
      struct.question = iprot.readString();
      struct.setQuestionIsSet(true);
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.topic = iprot.readString();
        struct.setTopicIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list37 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRING);
          struct.tags = new java.util.ArrayList<java.lang.String>(_list37.size);
          @org.apache.thrift.annotation.Nullable java.lang.String _elem38;
          for (int _i39 = 0; _i39 < _list37.size; ++_i39)
          {
            _elem38 = iprot.readString();
            struct.tags.add(_elem38);
          }
        }
        struct.setTagsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

