/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package now.calypso.backend.data;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class PublicPromptReactionEvent implements org.apache.thrift.TBase<PublicPromptReactionEvent, PublicPromptReactionEvent._Fields>, java.io.Serializable, Cloneable, Comparable<PublicPromptReactionEvent> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PublicPromptReactionEvent");

  private static final org.apache.thrift.protocol.TField VIEWER_ACCOUNT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("viewerAccountId", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField ANSWER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("answerId", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField PROMPT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("promptId", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField REACTION_FIELD_DESC = new org.apache.thrift.protocol.TField("reaction", org.apache.thrift.protocol.TType.I32, (short)4);
  private static final org.apache.thrift.protocol.TField REACTED_AT_FIELD_DESC = new org.apache.thrift.protocol.TField("reactedAt", org.apache.thrift.protocol.TType.I64, (short)5);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new PublicPromptReactionEventStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new PublicPromptReactionEventTupleSchemeFactory();

  public long viewerAccountId; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String answerId; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String promptId; // required
  /**
   * 
   * @see PromptReaction
   */
  public @org.apache.thrift.annotation.Nullable PromptReaction reaction; // required
  public long reactedAt; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    VIEWER_ACCOUNT_ID((short)1, "viewerAccountId"),
    ANSWER_ID((short)2, "answerId"),
    PROMPT_ID((short)3, "promptId"),
    /**
     * 
     * @see PromptReaction
     */
    REACTION((short)4, "reaction"),
    REACTED_AT((short)5, "reactedAt");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // VIEWER_ACCOUNT_ID
          return VIEWER_ACCOUNT_ID;
        case 2: // ANSWER_ID
          return ANSWER_ID;
        case 3: // PROMPT_ID
          return PROMPT_ID;
        case 4: // REACTION
          return REACTION;
        case 5: // REACTED_AT
          return REACTED_AT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __VIEWERACCOUNTID_ISSET_ID = 0;
  private static final int __REACTEDAT_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.VIEWER_ACCOUNT_ID, new org.apache.thrift.meta_data.FieldMetaData("viewerAccountId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "AccountId")));
    tmpMap.put(_Fields.ANSWER_ID, new org.apache.thrift.meta_data.FieldMetaData("answerId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PROMPT_ID, new org.apache.thrift.meta_data.FieldMetaData("promptId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.REACTION, new org.apache.thrift.meta_data.FieldMetaData("reaction", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, PromptReaction.class)));
    tmpMap.put(_Fields.REACTED_AT, new org.apache.thrift.meta_data.FieldMetaData("reactedAt", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "Timestamp")));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PublicPromptReactionEvent.class, metaDataMap);
  }

  public PublicPromptReactionEvent() {
  }

  public PublicPromptReactionEvent(
    long viewerAccountId,
    java.lang.String answerId,
    java.lang.String promptId,
    PromptReaction reaction,
    long reactedAt)
  {
    this();
    this.viewerAccountId = viewerAccountId;
    setViewerAccountIdIsSet(true);
    this.answerId = answerId;
    this.promptId = promptId;
    this.reaction = reaction;
    this.reactedAt = reactedAt;
    setReactedAtIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PublicPromptReactionEvent(PublicPromptReactionEvent other) {
    __isset_bitfield = other.__isset_bitfield;
    this.viewerAccountId = other.viewerAccountId;
    if (other.isSetAnswerId()) {
      this.answerId = other.answerId;
    }
    if (other.isSetPromptId()) {
      this.promptId = other.promptId;
    }
    if (other.isSetReaction()) {
      this.reaction = other.reaction;
    }
    this.reactedAt = other.reactedAt;
  }

  @Override
  public PublicPromptReactionEvent deepCopy() {
    return new PublicPromptReactionEvent(this);
  }

  @Override
  public void clear() {
    setViewerAccountIdIsSet(false);
    this.viewerAccountId = 0;
    this.answerId = null;
    this.promptId = null;
    this.reaction = null;
    setReactedAtIsSet(false);
    this.reactedAt = 0;
  }

  public long getViewerAccountId() {
    return this.viewerAccountId;
  }

  public PublicPromptReactionEvent setViewerAccountId(long viewerAccountId) {
    this.viewerAccountId = viewerAccountId;
    setViewerAccountIdIsSet(true);
    return this;
  }

  public void unsetViewerAccountId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __VIEWERACCOUNTID_ISSET_ID);
  }

  /** Returns true if field viewerAccountId is set (has been assigned a value) and false otherwise */
  public boolean isSetViewerAccountId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __VIEWERACCOUNTID_ISSET_ID);
  }

  public void setViewerAccountIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __VIEWERACCOUNTID_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getAnswerId() {
    return this.answerId;
  }

  public PublicPromptReactionEvent setAnswerId(@org.apache.thrift.annotation.Nullable java.lang.String answerId) {
    this.answerId = answerId;
    return this;
  }

  public void unsetAnswerId() {
    this.answerId = null;
  }

  /** Returns true if field answerId is set (has been assigned a value) and false otherwise */
  public boolean isSetAnswerId() {
    return this.answerId != null;
  }

  public void setAnswerIdIsSet(boolean value) {
    if (!value) {
      this.answerId = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getPromptId() {
    return this.promptId;
  }

  public PublicPromptReactionEvent setPromptId(@org.apache.thrift.annotation.Nullable java.lang.String promptId) {
    this.promptId = promptId;
    return this;
  }

  public void unsetPromptId() {
    this.promptId = null;
  }

  /** Returns true if field promptId is set (has been assigned a value) and false otherwise */
  public boolean isSetPromptId() {
    return this.promptId != null;
  }

  public void setPromptIdIsSet(boolean value) {
    if (!value) {
      this.promptId = null;
    }
  }

  /**
   * 
   * @see PromptReaction
   */
  @org.apache.thrift.annotation.Nullable
  public PromptReaction getReaction() {
    return this.reaction;
  }

  /**
   * 
   * @see PromptReaction
   */
  public PublicPromptReactionEvent setReaction(@org.apache.thrift.annotation.Nullable PromptReaction reaction) {
    this.reaction = reaction;
    return this;
  }

  public void unsetReaction() {
    this.reaction = null;
  }

  /** Returns true if field reaction is set (has been assigned a value) and false otherwise */
  public boolean isSetReaction() {
    return this.reaction != null;
  }

  public void setReactionIsSet(boolean value) {
    if (!value) {
      this.reaction = null;
    }
  }

  public long getReactedAt() {
    return this.reactedAt;
  }

  public PublicPromptReactionEvent setReactedAt(long reactedAt) {
    this.reactedAt = reactedAt;
    setReactedAtIsSet(true);
    return this;
  }

  public void unsetReactedAt() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __REACTEDAT_ISSET_ID);
  }

  /** Returns true if field reactedAt is set (has been assigned a value) and false otherwise */
  public boolean isSetReactedAt() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __REACTEDAT_ISSET_ID);
  }

  public void setReactedAtIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __REACTEDAT_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case VIEWER_ACCOUNT_ID:
      if (value == null) {
        unsetViewerAccountId();
      } else {
        setViewerAccountId((java.lang.Long)value);
      }
      break;

    case ANSWER_ID:
      if (value == null) {
        unsetAnswerId();
      } else {
        setAnswerId((java.lang.String)value);
      }
      break;

    case PROMPT_ID:
      if (value == null) {
        unsetPromptId();
      } else {
        setPromptId((java.lang.String)value);
      }
      break;

    case REACTION:
      if (value == null) {
        unsetReaction();
      } else {
        setReaction((PromptReaction)value);
      }
      break;

    case REACTED_AT:
      if (value == null) {
        unsetReactedAt();
      } else {
        setReactedAt((java.lang.Long)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case VIEWER_ACCOUNT_ID:
      return getViewerAccountId();

    case ANSWER_ID:
      return getAnswerId();

    case PROMPT_ID:
      return getPromptId();

    case REACTION:
      return getReaction();

    case REACTED_AT:
      return getReactedAt();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case VIEWER_ACCOUNT_ID:
      return isSetViewerAccountId();
    case ANSWER_ID:
      return isSetAnswerId();
    case PROMPT_ID:
      return isSetPromptId();
    case REACTION:
      return isSetReaction();
    case REACTED_AT:
      return isSetReactedAt();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof PublicPromptReactionEvent)
      return this.equals((PublicPromptReactionEvent)that);
    return false;
  }

  public boolean equals(PublicPromptReactionEvent that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_viewerAccountId = true;
    boolean that_present_viewerAccountId = true;
    if (this_present_viewerAccountId || that_present_viewerAccountId) {
      if (!(this_present_viewerAccountId && that_present_viewerAccountId))
        return false;
      if (this.viewerAccountId != that.viewerAccountId)
        return false;
    }

    boolean this_present_answerId = true && this.isSetAnswerId();
    boolean that_present_answerId = true && that.isSetAnswerId();
    if (this_present_answerId || that_present_answerId) {
      if (!(this_present_answerId && that_present_answerId))
        return false;
      if (!this.answerId.equals(that.answerId))
        return false;
    }

    boolean this_present_promptId = true && this.isSetPromptId();
    boolean that_present_promptId = true && that.isSetPromptId();
    if (this_present_promptId || that_present_promptId) {
      if (!(this_present_promptId && that_present_promptId))
        return false;
      if (!this.promptId.equals(that.promptId))
        return false;
    }

    boolean this_present_reaction = true && this.isSetReaction();
    boolean that_present_reaction = true && that.isSetReaction();
    if (this_present_reaction || that_present_reaction) {
      if (!(this_present_reaction && that_present_reaction))
        return false;
      if (!this.reaction.equals(that.reaction))
        return false;
    }

    boolean this_present_reactedAt = true;
    boolean that_present_reactedAt = true;
    if (this_present_reactedAt || that_present_reactedAt) {
      if (!(this_present_reactedAt && that_present_reactedAt))
        return false;
      if (this.reactedAt != that.reactedAt)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(viewerAccountId);

    hashCode = hashCode * 8191 + ((isSetAnswerId()) ? 131071 : 524287);
    if (isSetAnswerId())
      hashCode = hashCode * 8191 + answerId.hashCode();

    hashCode = hashCode * 8191 + ((isSetPromptId()) ? 131071 : 524287);
    if (isSetPromptId())
      hashCode = hashCode * 8191 + promptId.hashCode();

    hashCode = hashCode * 8191 + ((isSetReaction()) ? 131071 : 524287);
    if (isSetReaction())
      hashCode = hashCode * 8191 + reaction.getValue();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(reactedAt);

    return hashCode;
  }

  @Override
  public int compareTo(PublicPromptReactionEvent other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetViewerAccountId(), other.isSetViewerAccountId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetViewerAccountId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.viewerAccountId, other.viewerAccountId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetAnswerId(), other.isSetAnswerId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAnswerId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.answerId, other.answerId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetPromptId(), other.isSetPromptId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPromptId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.promptId, other.promptId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetReaction(), other.isSetReaction());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReaction()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.reaction, other.reaction);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetReactedAt(), other.isSetReactedAt());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReactedAt()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.reactedAt, other.reactedAt);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("PublicPromptReactionEvent(");
    boolean first = true;

    sb.append("viewerAccountId:");
    sb.append(this.viewerAccountId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("answerId:");
    if (this.answerId == null) {
      sb.append("null");
    } else {
      sb.append(this.answerId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("promptId:");
    if (this.promptId == null) {
      sb.append("null");
    } else {
      sb.append(this.promptId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("reaction:");
    if (this.reaction == null) {
      sb.append("null");
    } else {
      sb.append(this.reaction);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("reactedAt:");
    sb.append(this.reactedAt);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'viewerAccountId' because it's a primitive and you chose the non-beans generator.
    if (answerId == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'answerId' was not present! Struct: " + toString());
    }
    if (promptId == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'promptId' was not present! Struct: " + toString());
    }
    if (reaction == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'reaction' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'reactedAt' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PublicPromptReactionEventStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public PublicPromptReactionEventStandardScheme getScheme() {
      return new PublicPromptReactionEventStandardScheme();
    }
  }

  private static class PublicPromptReactionEventStandardScheme extends org.apache.thrift.scheme.StandardScheme<PublicPromptReactionEvent> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, PublicPromptReactionEvent struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // VIEWER_ACCOUNT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.viewerAccountId = iprot.readI64();
              struct.setViewerAccountIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // ANSWER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.answerId = iprot.readString();
              struct.setAnswerIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PROMPT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.promptId = iprot.readString();
              struct.setPromptIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // REACTION
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.reaction = now.calypso.backend.data.PromptReaction.findByValue(iprot.readI32());
              struct.setReactionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // REACTED_AT
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.reactedAt = iprot.readI64();
              struct.setReactedAtIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetViewerAccountId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'viewerAccountId' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetReactedAt()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'reactedAt' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, PublicPromptReactionEvent struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(VIEWER_ACCOUNT_ID_FIELD_DESC);
      oprot.writeI64(struct.viewerAccountId);
      oprot.writeFieldEnd();
      if (struct.answerId != null) {
        oprot.writeFieldBegin(ANSWER_ID_FIELD_DESC);
        oprot.writeString(struct.answerId);
        oprot.writeFieldEnd();
      }
      if (struct.promptId != null) {
        oprot.writeFieldBegin(PROMPT_ID_FIELD_DESC);
        oprot.writeString(struct.promptId);
        oprot.writeFieldEnd();
      }
      if (struct.reaction != null) {
        oprot.writeFieldBegin(REACTION_FIELD_DESC);
        oprot.writeI32(struct.reaction.getValue());
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(REACTED_AT_FIELD_DESC);
      oprot.writeI64(struct.reactedAt);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PublicPromptReactionEventTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public PublicPromptReactionEventTupleScheme getScheme() {
      return new PublicPromptReactionEventTupleScheme();
    }
  }

  private static class PublicPromptReactionEventTupleScheme extends org.apache.thrift.scheme.TupleScheme<PublicPromptReactionEvent> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PublicPromptReactionEvent struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeI64(struct.viewerAccountId);
      oprot.writeString(struct.answerId);
      oprot.writeString(struct.promptId);
      oprot.writeI32(struct.reaction.getValue());
      oprot.writeI64(struct.reactedAt);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PublicPromptReactionEvent struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.viewerAccountId = iprot.readI64();
      struct.setViewerAccountIdIsSet(true);
      struct.answerId = iprot.readString();
      struct.setAnswerIdIsSet(true);
      struct.promptId = iprot.readString();
      struct.setPromptIdIsSet(true);
      struct.reaction = now.calypso.backend.data.PromptReaction.findByValue(iprot.readI32());
      struct.setReactionIsSet(true);
      struct.reactedAt = iprot.readI64();
      struct.setReactedAtIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

