/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package now.calypso.backend.data;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class PublicPromptFeedCard implements org.apache.thrift.TBase<PublicPromptFeedCard, PublicPromptFeedCard._Fields>, java.io.Serializable, Cloneable, Comparable<PublicPromptFeedCard> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PublicPromptFeedCard");

  private static final org.apache.thrift.protocol.TField ANSWER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("answerId", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField PROMPT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("promptId", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField PROMPT_TEXT_FIELD_DESC = new org.apache.thrift.protocol.TField("promptText", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField BODY_FIELD_DESC = new org.apache.thrift.protocol.TField("body", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField CREATED_AT_FIELD_DESC = new org.apache.thrift.protocol.TField("createdAt", org.apache.thrift.protocol.TType.I64, (short)5);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new PublicPromptFeedCardStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new PublicPromptFeedCardTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String answerId; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String promptId; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String promptText; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String body; // required
  public long createdAt; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ANSWER_ID((short)1, "answerId"),
    PROMPT_ID((short)2, "promptId"),
    PROMPT_TEXT((short)3, "promptText"),
    BODY((short)4, "body"),
    CREATED_AT((short)5, "createdAt");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ANSWER_ID
          return ANSWER_ID;
        case 2: // PROMPT_ID
          return PROMPT_ID;
        case 3: // PROMPT_TEXT
          return PROMPT_TEXT;
        case 4: // BODY
          return BODY;
        case 5: // CREATED_AT
          return CREATED_AT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __CREATEDAT_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ANSWER_ID, new org.apache.thrift.meta_data.FieldMetaData("answerId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PROMPT_ID, new org.apache.thrift.meta_data.FieldMetaData("promptId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PROMPT_TEXT, new org.apache.thrift.meta_data.FieldMetaData("promptText", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.BODY, new org.apache.thrift.meta_data.FieldMetaData("body", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CREATED_AT, new org.apache.thrift.meta_data.FieldMetaData("createdAt", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "Timestamp")));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PublicPromptFeedCard.class, metaDataMap);
  }

  public PublicPromptFeedCard() {
  }

  public PublicPromptFeedCard(
    java.lang.String answerId,
    java.lang.String promptId,
    java.lang.String promptText,
    java.lang.String body,
    long createdAt)
  {
    this();
    this.answerId = answerId;
    this.promptId = promptId;
    this.promptText = promptText;
    this.body = body;
    this.createdAt = createdAt;
    setCreatedAtIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PublicPromptFeedCard(PublicPromptFeedCard other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetAnswerId()) {
      this.answerId = other.answerId;
    }
    if (other.isSetPromptId()) {
      this.promptId = other.promptId;
    }
    if (other.isSetPromptText()) {
      this.promptText = other.promptText;
    }
    if (other.isSetBody()) {
      this.body = other.body;
    }
    this.createdAt = other.createdAt;
  }

  @Override
  public PublicPromptFeedCard deepCopy() {
    return new PublicPromptFeedCard(this);
  }

  @Override
  public void clear() {
    this.answerId = null;
    this.promptId = null;
    this.promptText = null;
    this.body = null;
    setCreatedAtIsSet(false);
    this.createdAt = 0;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getAnswerId() {
    return this.answerId;
  }

  public PublicPromptFeedCard setAnswerId(@org.apache.thrift.annotation.Nullable java.lang.String answerId) {
    this.answerId = answerId;
    return this;
  }

  public void unsetAnswerId() {
    this.answerId = null;
  }

  /** Returns true if field answerId is set (has been assigned a value) and false otherwise */
  public boolean isSetAnswerId() {
    return this.answerId != null;
  }

  public void setAnswerIdIsSet(boolean value) {
    if (!value) {
      this.answerId = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getPromptId() {
    return this.promptId;
  }

  public PublicPromptFeedCard setPromptId(@org.apache.thrift.annotation.Nullable java.lang.String promptId) {
    this.promptId = promptId;
    return this;
  }

  public void unsetPromptId() {
    this.promptId = null;
  }

  /** Returns true if field promptId is set (has been assigned a value) and false otherwise */
  public boolean isSetPromptId() {
    return this.promptId != null;
  }

  public void setPromptIdIsSet(boolean value) {
    if (!value) {
      this.promptId = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getPromptText() {
    return this.promptText;
  }

  public PublicPromptFeedCard setPromptText(@org.apache.thrift.annotation.Nullable java.lang.String promptText) {
    this.promptText = promptText;
    return this;
  }

  public void unsetPromptText() {
    this.promptText = null;
  }

  /** Returns true if field promptText is set (has been assigned a value) and false otherwise */
  public boolean isSetPromptText() {
    return this.promptText != null;
  }

  public void setPromptTextIsSet(boolean value) {
    if (!value) {
      this.promptText = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getBody() {
    return this.body;
  }

  public PublicPromptFeedCard setBody(@org.apache.thrift.annotation.Nullable java.lang.String body) {
    this.body = body;
    return this;
  }

  public void unsetBody() {
    this.body = null;
  }

  /** Returns true if field body is set (has been assigned a value) and false otherwise */
  public boolean isSetBody() {
    return this.body != null;
  }

  public void setBodyIsSet(boolean value) {
    if (!value) {
      this.body = null;
    }
  }

  public long getCreatedAt() {
    return this.createdAt;
  }

  public PublicPromptFeedCard setCreatedAt(long createdAt) {
    this.createdAt = createdAt;
    setCreatedAtIsSet(true);
    return this;
  }

  public void unsetCreatedAt() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CREATEDAT_ISSET_ID);
  }

  /** Returns true if field createdAt is set (has been assigned a value) and false otherwise */
  public boolean isSetCreatedAt() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CREATEDAT_ISSET_ID);
  }

  public void setCreatedAtIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CREATEDAT_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case ANSWER_ID:
      if (value == null) {
        unsetAnswerId();
      } else {
        setAnswerId((java.lang.String)value);
      }
      break;

    case PROMPT_ID:
      if (value == null) {
        unsetPromptId();
      } else {
        setPromptId((java.lang.String)value);
      }
      break;

    case PROMPT_TEXT:
      if (value == null) {
        unsetPromptText();
      } else {
        setPromptText((java.lang.String)value);
      }
      break;

    case BODY:
      if (value == null) {
        unsetBody();
      } else {
        setBody((java.lang.String)value);
      }
      break;

    case CREATED_AT:
      if (value == null) {
        unsetCreatedAt();
      } else {
        setCreatedAt((java.lang.Long)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ANSWER_ID:
      return getAnswerId();

    case PROMPT_ID:
      return getPromptId();

    case PROMPT_TEXT:
      return getPromptText();

    case BODY:
      return getBody();

    case CREATED_AT:
      return getCreatedAt();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ANSWER_ID:
      return isSetAnswerId();
    case PROMPT_ID:
      return isSetPromptId();
    case PROMPT_TEXT:
      return isSetPromptText();
    case BODY:
      return isSetBody();
    case CREATED_AT:
      return isSetCreatedAt();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof PublicPromptFeedCard)
      return this.equals((PublicPromptFeedCard)that);
    return false;
  }

  public boolean equals(PublicPromptFeedCard that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_answerId = true && this.isSetAnswerId();
    boolean that_present_answerId = true && that.isSetAnswerId();
    if (this_present_answerId || that_present_answerId) {
      if (!(this_present_answerId && that_present_answerId))
        return false;
      if (!this.answerId.equals(that.answerId))
        return false;
    }

    boolean this_present_promptId = true && this.isSetPromptId();
    boolean that_present_promptId = true && that.isSetPromptId();
    if (this_present_promptId || that_present_promptId) {
      if (!(this_present_promptId && that_present_promptId))
        return false;
      if (!this.promptId.equals(that.promptId))
        return false;
    }

    boolean this_present_promptText = true && this.isSetPromptText();
    boolean that_present_promptText = true && that.isSetPromptText();
    if (this_present_promptText || that_present_promptText) {
      if (!(this_present_promptText && that_present_promptText))
        return false;
      if (!this.promptText.equals(that.promptText))
        return false;
    }

    boolean this_present_body = true && this.isSetBody();
    boolean that_present_body = true && that.isSetBody();
    if (this_present_body || that_present_body) {
      if (!(this_present_body && that_present_body))
        return false;
      if (!this.body.equals(that.body))
        return false;
    }

    boolean this_present_createdAt = true;
    boolean that_present_createdAt = true;
    if (this_present_createdAt || that_present_createdAt) {
      if (!(this_present_createdAt && that_present_createdAt))
        return false;
      if (this.createdAt != that.createdAt)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetAnswerId()) ? 131071 : 524287);
    if (isSetAnswerId())
      hashCode = hashCode * 8191 + answerId.hashCode();

    hashCode = hashCode * 8191 + ((isSetPromptId()) ? 131071 : 524287);
    if (isSetPromptId())
      hashCode = hashCode * 8191 + promptId.hashCode();

    hashCode = hashCode * 8191 + ((isSetPromptText()) ? 131071 : 524287);
    if (isSetPromptText())
      hashCode = hashCode * 8191 + promptText.hashCode();

    hashCode = hashCode * 8191 + ((isSetBody()) ? 131071 : 524287);
    if (isSetBody())
      hashCode = hashCode * 8191 + body.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(createdAt);

    return hashCode;
  }

  @Override
  public int compareTo(PublicPromptFeedCard other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetAnswerId(), other.isSetAnswerId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAnswerId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.answerId, other.answerId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetPromptId(), other.isSetPromptId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPromptId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.promptId, other.promptId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetPromptText(), other.isSetPromptText());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPromptText()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.promptText, other.promptText);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetBody(), other.isSetBody());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBody()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.body, other.body);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetCreatedAt(), other.isSetCreatedAt());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreatedAt()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.createdAt, other.createdAt);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("PublicPromptFeedCard(");
    boolean first = true;

    sb.append("answerId:");
    if (this.answerId == null) {
      sb.append("null");
    } else {
      sb.append(this.answerId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("promptId:");
    if (this.promptId == null) {
      sb.append("null");
    } else {
      sb.append(this.promptId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("promptText:");
    if (this.promptText == null) {
      sb.append("null");
    } else {
      sb.append(this.promptText);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("body:");
    if (this.body == null) {
      sb.append("null");
    } else {
      sb.append(this.body);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("createdAt:");
    sb.append(this.createdAt);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (answerId == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'answerId' was not present! Struct: " + toString());
    }
    if (promptId == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'promptId' was not present! Struct: " + toString());
    }
    if (promptText == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'promptText' was not present! Struct: " + toString());
    }
    if (body == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'body' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'createdAt' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PublicPromptFeedCardStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public PublicPromptFeedCardStandardScheme getScheme() {
      return new PublicPromptFeedCardStandardScheme();
    }
  }

  private static class PublicPromptFeedCardStandardScheme extends org.apache.thrift.scheme.StandardScheme<PublicPromptFeedCard> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, PublicPromptFeedCard struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ANSWER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.answerId = iprot.readString();
              struct.setAnswerIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PROMPT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.promptId = iprot.readString();
              struct.setPromptIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PROMPT_TEXT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.promptText = iprot.readString();
              struct.setPromptTextIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // BODY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.body = iprot.readString();
              struct.setBodyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // CREATED_AT
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.createdAt = iprot.readI64();
              struct.setCreatedAtIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetCreatedAt()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'createdAt' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, PublicPromptFeedCard struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.answerId != null) {
        oprot.writeFieldBegin(ANSWER_ID_FIELD_DESC);
        oprot.writeString(struct.answerId);
        oprot.writeFieldEnd();
      }
      if (struct.promptId != null) {
        oprot.writeFieldBegin(PROMPT_ID_FIELD_DESC);
        oprot.writeString(struct.promptId);
        oprot.writeFieldEnd();
      }
      if (struct.promptText != null) {
        oprot.writeFieldBegin(PROMPT_TEXT_FIELD_DESC);
        oprot.writeString(struct.promptText);
        oprot.writeFieldEnd();
      }
      if (struct.body != null) {
        oprot.writeFieldBegin(BODY_FIELD_DESC);
        oprot.writeString(struct.body);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(CREATED_AT_FIELD_DESC);
      oprot.writeI64(struct.createdAt);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PublicPromptFeedCardTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public PublicPromptFeedCardTupleScheme getScheme() {
      return new PublicPromptFeedCardTupleScheme();
    }
  }

  private static class PublicPromptFeedCardTupleScheme extends org.apache.thrift.scheme.TupleScheme<PublicPromptFeedCard> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PublicPromptFeedCard struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.answerId);
      oprot.writeString(struct.promptId);
      oprot.writeString(struct.promptText);
      oprot.writeString(struct.body);
      oprot.writeI64(struct.createdAt);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PublicPromptFeedCard struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.answerId = iprot.readString();
      struct.setAnswerIdIsSet(true);
      struct.promptId = iprot.readString();
      struct.setPromptIdIsSet(true);
      struct.promptText = iprot.readString();
      struct.setPromptTextIsSet(true);
      struct.body = iprot.readString();
      struct.setBodyIsSet(true);
      struct.createdAt = iprot.readI64();
      struct.setCreatedAtIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

