/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package now.calypso.backend.data;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class ServedPairs implements org.apache.thrift.TBase<ServedPairs, ServedPairs._Fields>, java.io.Serializable, Cloneable, Comparable<ServedPairs> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ServedPairs");

  private static final org.apache.thrift.protocol.TField ACCOUNT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("accountId", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField TARGET_IDS_FIELD_DESC = new org.apache.thrift.protocol.TField("targetIds", org.apache.thrift.protocol.TType.LIST, (short)2);
  private static final org.apache.thrift.protocol.TField SERVED_AT_FIELD_DESC = new org.apache.thrift.protocol.TField("servedAt", org.apache.thrift.protocol.TType.I64, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ServedPairsStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ServedPairsTupleSchemeFactory();

  public long accountId; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<java.lang.Long> targetIds; // required
  public long servedAt; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ACCOUNT_ID((short)1, "accountId"),
    TARGET_IDS((short)2, "targetIds"),
    SERVED_AT((short)3, "servedAt");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ACCOUNT_ID
          return ACCOUNT_ID;
        case 2: // TARGET_IDS
          return TARGET_IDS;
        case 3: // SERVED_AT
          return SERVED_AT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ACCOUNTID_ISSET_ID = 0;
  private static final int __SERVEDAT_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ACCOUNT_ID, new org.apache.thrift.meta_data.FieldMetaData("accountId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "AccountId")));
    tmpMap.put(_Fields.TARGET_IDS, new org.apache.thrift.meta_data.FieldMetaData("targetIds", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64            , "AccountId"))));
    tmpMap.put(_Fields.SERVED_AT, new org.apache.thrift.meta_data.FieldMetaData("servedAt", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "Timestamp")));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ServedPairs.class, metaDataMap);
  }

  public ServedPairs() {
  }

  public ServedPairs(
    long accountId,
    java.util.List<java.lang.Long> targetIds,
    long servedAt)
  {
    this();
    this.accountId = accountId;
    setAccountIdIsSet(true);
    this.targetIds = targetIds;
    this.servedAt = servedAt;
    setServedAtIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ServedPairs(ServedPairs other) {
    __isset_bitfield = other.__isset_bitfield;
    this.accountId = other.accountId;
    if (other.isSetTargetIds()) {
      java.util.List<java.lang.Long> __this__targetIds = new java.util.ArrayList<java.lang.Long>(other.targetIds.size());
      for (java.lang.Long other_element : other.targetIds) {
        __this__targetIds.add(other_element);
      }
      this.targetIds = __this__targetIds;
    }
    this.servedAt = other.servedAt;
  }

  @Override
  public ServedPairs deepCopy() {
    return new ServedPairs(this);
  }

  @Override
  public void clear() {
    setAccountIdIsSet(false);
    this.accountId = 0;
    this.targetIds = null;
    setServedAtIsSet(false);
    this.servedAt = 0;
  }

  public long getAccountId() {
    return this.accountId;
  }

  public ServedPairs setAccountId(long accountId) {
    this.accountId = accountId;
    setAccountIdIsSet(true);
    return this;
  }

  public void unsetAccountId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ACCOUNTID_ISSET_ID);
  }

  /** Returns true if field accountId is set (has been assigned a value) and false otherwise */
  public boolean isSetAccountId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ACCOUNTID_ISSET_ID);
  }

  public void setAccountIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ACCOUNTID_ISSET_ID, value);
  }

  public int getTargetIdsSize() {
    return (this.targetIds == null) ? 0 : this.targetIds.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.lang.Long> getTargetIdsIterator() {
    return (this.targetIds == null) ? null : this.targetIds.iterator();
  }

  public void addToTargetIds(long elem) {
    if (this.targetIds == null) {
      this.targetIds = new java.util.ArrayList<java.lang.Long>();
    }
    this.targetIds.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<java.lang.Long> getTargetIds() {
    return this.targetIds;
  }

  public ServedPairs setTargetIds(@org.apache.thrift.annotation.Nullable java.util.List<java.lang.Long> targetIds) {
    this.targetIds = targetIds;
    return this;
  }

  public void unsetTargetIds() {
    this.targetIds = null;
  }

  /** Returns true if field targetIds is set (has been assigned a value) and false otherwise */
  public boolean isSetTargetIds() {
    return this.targetIds != null;
  }

  public void setTargetIdsIsSet(boolean value) {
    if (!value) {
      this.targetIds = null;
    }
  }

  public long getServedAt() {
    return this.servedAt;
  }

  public ServedPairs setServedAt(long servedAt) {
    this.servedAt = servedAt;
    setServedAtIsSet(true);
    return this;
  }

  public void unsetServedAt() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SERVEDAT_ISSET_ID);
  }

  /** Returns true if field servedAt is set (has been assigned a value) and false otherwise */
  public boolean isSetServedAt() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SERVEDAT_ISSET_ID);
  }

  public void setServedAtIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SERVEDAT_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case ACCOUNT_ID:
      if (value == null) {
        unsetAccountId();
      } else {
        setAccountId((java.lang.Long)value);
      }
      break;

    case TARGET_IDS:
      if (value == null) {
        unsetTargetIds();
      } else {
        setTargetIds((java.util.List<java.lang.Long>)value);
      }
      break;

    case SERVED_AT:
      if (value == null) {
        unsetServedAt();
      } else {
        setServedAt((java.lang.Long)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ACCOUNT_ID:
      return getAccountId();

    case TARGET_IDS:
      return getTargetIds();

    case SERVED_AT:
      return getServedAt();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ACCOUNT_ID:
      return isSetAccountId();
    case TARGET_IDS:
      return isSetTargetIds();
    case SERVED_AT:
      return isSetServedAt();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof ServedPairs)
      return this.equals((ServedPairs)that);
    return false;
  }

  public boolean equals(ServedPairs that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_accountId = true;
    boolean that_present_accountId = true;
    if (this_present_accountId || that_present_accountId) {
      if (!(this_present_accountId && that_present_accountId))
        return false;
      if (this.accountId != that.accountId)
        return false;
    }

    boolean this_present_targetIds = true && this.isSetTargetIds();
    boolean that_present_targetIds = true && that.isSetTargetIds();
    if (this_present_targetIds || that_present_targetIds) {
      if (!(this_present_targetIds && that_present_targetIds))
        return false;
      if (!this.targetIds.equals(that.targetIds))
        return false;
    }

    boolean this_present_servedAt = true;
    boolean that_present_servedAt = true;
    if (this_present_servedAt || that_present_servedAt) {
      if (!(this_present_servedAt && that_present_servedAt))
        return false;
      if (this.servedAt != that.servedAt)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(accountId);

    hashCode = hashCode * 8191 + ((isSetTargetIds()) ? 131071 : 524287);
    if (isSetTargetIds())
      hashCode = hashCode * 8191 + targetIds.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(servedAt);

    return hashCode;
  }

  @Override
  public int compareTo(ServedPairs other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetAccountId(), other.isSetAccountId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAccountId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.accountId, other.accountId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetTargetIds(), other.isSetTargetIds());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTargetIds()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.targetIds, other.targetIds);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetServedAt(), other.isSetServedAt());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetServedAt()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.servedAt, other.servedAt);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("ServedPairs(");
    boolean first = true;

    sb.append("accountId:");
    sb.append(this.accountId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("targetIds:");
    if (this.targetIds == null) {
      sb.append("null");
    } else {
      sb.append(this.targetIds);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("servedAt:");
    sb.append(this.servedAt);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'accountId' because it's a primitive and you chose the non-beans generator.
    if (targetIds == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'targetIds' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'servedAt' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ServedPairsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public ServedPairsStandardScheme getScheme() {
      return new ServedPairsStandardScheme();
    }
  }

  private static class ServedPairsStandardScheme extends org.apache.thrift.scheme.StandardScheme<ServedPairs> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, ServedPairs struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ACCOUNT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.accountId = iprot.readI64();
              struct.setAccountIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TARGET_IDS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list40 = iprot.readListBegin();
                struct.targetIds = new java.util.ArrayList<java.lang.Long>(_list40.size);
                long _elem41;
                for (int _i42 = 0; _i42 < _list40.size; ++_i42)
                {
                  _elem41 = iprot.readI64();
                  struct.targetIds.add(_elem41);
                }
                iprot.readListEnd();
              }
              struct.setTargetIdsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // SERVED_AT
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.servedAt = iprot.readI64();
              struct.setServedAtIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetAccountId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'accountId' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetServedAt()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'servedAt' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, ServedPairs struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ACCOUNT_ID_FIELD_DESC);
      oprot.writeI64(struct.accountId);
      oprot.writeFieldEnd();
      if (struct.targetIds != null) {
        oprot.writeFieldBegin(TARGET_IDS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I64, struct.targetIds.size()));
          for (long _iter43 : struct.targetIds)
          {
            oprot.writeI64(_iter43);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(SERVED_AT_FIELD_DESC);
      oprot.writeI64(struct.servedAt);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ServedPairsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public ServedPairsTupleScheme getScheme() {
      return new ServedPairsTupleScheme();
    }
  }

  private static class ServedPairsTupleScheme extends org.apache.thrift.scheme.TupleScheme<ServedPairs> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ServedPairs struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeI64(struct.accountId);
      {
        oprot.writeI32(struct.targetIds.size());
        for (long _iter44 : struct.targetIds)
        {
          oprot.writeI64(_iter44);
        }
      }
      oprot.writeI64(struct.servedAt);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ServedPairs struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.accountId = iprot.readI64();
      struct.setAccountIdIsSet(true);
      {
        org.apache.thrift.protocol.TList _list45 = iprot.readListBegin(org.apache.thrift.protocol.TType.I64);
        struct.targetIds = new java.util.ArrayList<java.lang.Long>(_list45.size);
        long _elem46;
        for (int _i47 = 0; _i47 < _list45.size; ++_i47)
        {
          _elem46 = iprot.readI64();
          struct.targetIds.add(_elem46);
        }
      }
      struct.setTargetIdsIsSet(true);
      struct.servedAt = iprot.readI64();
      struct.setServedAtIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

