/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package now.calypso.backend.data;


public enum SignalIntent implements org.apache.thrift.TEnum {
  SELF(1),
  SEEKING(2),
  META(3),
  BOTH(4);

  private final int value;

  private SignalIntent(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static SignalIntent findByValue(int value) { 
    switch (value) {
      case 1:
        return SELF;
      case 2:
        return SEEKING;
      case 3:
        return META;
      case 4:
        return BOTH;
      default:
        return null;
    }
  }
}
